Repository bloomberg/comdb2, pull requests merged in 2018-05, with the labels that each got.

#841 dlmalloc: Check for wrap around 0.
  dlmalloc/dlmalloc.c
Labels: bug

#842 cdb2jdbc: Configurable timeouts.
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/BBSysUtils.java
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/Comdb2Connection.java
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/Comdb2Handle.java
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/Comdb2Statement.java
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/Driver.java
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/SockIO.java
  cdb2jdbc/src/test/java/com/bloomberg/comdb2/jdbc/TimeoutTest.java
Labels: JDBC, enhancement

#843 @ls/@describe shortcuts to list and describe tables.
  tests/cdb2sql.test/Makefile
  tests/cdb2sql.test/README
  tests/cdb2sql.test/lrl.options
  tests/cdb2sql.test/runit
  tests/cdb2sql.test/t00.expected
  tests/cdb2sql.test/t00.sql
  tools/cdb2sql/cdb2sql.c
Labels: enhancement

#880 bdb: Fix race between election and shutdown.
  bdb/file.c
  bdb/rep.c
Labels: bug

#860 dlmalloc: Minor tweak and cleanup.
  dlmalloc/dlmalloc.c
  dlmalloc/dlmalloc.h
  dlmalloc/test.c
Labels: cleanup

#874 cdb2jdbc: Check comdb2db port before connecting.
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/Comdb2Connection.java
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/Comdb2Handle.java
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/Comdb2Statement.java
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/DatabaseDiscovery.java
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/NoDbHostFoundException.java
  cdb2jdbc/src/test/java/com/bloomberg/comdb2/jdbc/DatabaseDiscoveryTest.java
  cdb2jdbc/src/test/java/com/bloomberg/comdb2/jdbc/PreparedStatementTest.java
Labels: JDBC, bug

#886 osql: Get rid of too-big logging.
  db/osqlblockproc.c
Labels: cleanup

#858 DDL: Provide a tunable to control automatic dropping of dependent objects on DROP
  db/config.c
  db/db_tunables.c
  db/db_tunables.h
  sqlite/comdb2build.c
  tests/ddl_no_cascade_drop.test/Makefile
  tests/ddl_no_cascade_drop.test/README
  tests/ddl_no_cascade_drop.test/lrl.options
  tests/ddl_no_cascade_drop.test/runit
  tests/ddl_no_cascade_drop.test/t01_alter_table.expected
  tests/ddl_no_cascade_drop.test/t01_alter_table.sql
  tests/tunables.test/t00_all_tunables.expected
Labels: R7, enhancement

#906 Fix querytimeout assignment in Comdb2Statement construction
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/Comdb2Statement.java
Labels: JDBC, bug
