Repository bloomberg/comdb2, pull requests merged in 2018-03, with the labels that each got.

#757 cdb2jdbc: Porting cdb2_clear_ack change to cdb2jdbc.
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/Comdb2Connection.java
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/Comdb2Handle.java
Labels: JDBC, enhancement, port

#759 Remove obsolete tunables/attributes/switches.
  bb/debug_switches.c
  bbinc/debug_switches.h
  bdb/attr.h
  bdb/ll.c
  bdb/rowlocks.c
  berkdb/rep/rep_record.c
  db/comdb2.c
  db/comdb2.h
  db/config.c
  db/db_tunables.c
  db/db_tunables.h
  db/glue.c
  db/prefault_helper.c
  db/process_message.c
  docs/aspell.en.pws
  docs/pages/config/config_files.md
  sqlite/sqlite_tunables.h
  tests/simple_ssl.test/runit
  tests/tmptbl_starve.test/Makefile
  tests/tunables.test/t00_all_tunables.expected
  tests/tunables.test/t01_dyn_tunables.expected
  tests/tunables.test/t01_dyn_tunables.sql
Labels: cleanup

#761 dlmalloc: Excessively high memory allocation due to a miscalculation in realloc().
  dlmalloc/dlmalloc.c
Labels: bug

#766 Disable comdb2_pthread_create.
  CMakeLists.txt
  bb/thdpool.c
  mem/mem.c
Labels: enhancement

#767 SSL Enhancements.
  bb/ssl_io.c
  bb/ssl_support.c
  bbinc/ssl_support.h
  cdb2api/cdb2api.c
  db/ssl_bend.c
  db/ssl_bend.h
  docs/pages/config/ssl.md
Labels: enhancement

#760 Don't truncate pthread_self() to a 32-bit interger.
  bdb/bdblock.c
  bdb/rep.c
  db/constraints.c
  db/tag.c
Labels: bug

#769 Fix the return type of intervaldsus in comdb2api.
  db/sqlinterfaces.c
Labels: bug

#777 Minor tweaks to auto analyze.
  db/autoanalyze.c
Labels: cleanup

#551 Add hibernate dialect
  .gitignore
  contrib/cdb2hibernatedialect/build.gradle
  contrib/cdb2hibernatedialect/gradle.properties
  contrib/cdb2hibernatedialect/gradle/wrapper/gradle-wrapper.jar
  contrib/cdb2hibernatedialect/gradle/wrapper/gradle-wrapper.properties
  contrib/cdb2hibernatedialect/gradlew
  contrib/cdb2hibernatedialect/gradlew.bat
  contrib/cdb2hibernatedialect/pom.xml
  contrib/cdb2hibernatedialect/settings.gradle
  contrib/cdb2hibernatedialect/src/main/assembly/dist.xml
  contrib/cdb2hibernatedialect/src/main/java/org/hibernate/dialect/Comdb2Dialect.java
Labels: JDBC, enhancement

#789 bdb: Fix bdb_lock_destructor error on clean exit.
  bdb/rep.c
Labels: bug
