Repository bloomberg/comdb2, pull requests merged in 2018-10, with the labels that each got.

#1131 bdb: Fix possible infinite loop on mastership change.
  bdb/file.c
Labels: bug

#1132 db: Fix 10-second write timeout on connections obtained from the socket pool.
  db/sqlinterfaces.c
  tests/nowritetimeout.test/Makefile
  tests/nowritetimeout.test/runit
  tests/tools/CMakeLists.txt
  tests/tools/nowritetimeout.c
Labels: bug

#1147 berkdb: Check ALL hash buckets if not enough space for a new page in the buffer pool.
  berkdb/mp/mp_alloc.c
Labels: bug

#1144 Support for connection initialization statements.
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/UnpooledDataSource.java
  cdb2jdbc/src/test/java/com/bloomberg/comdb2/jdbc/UnpooledDataSourceTest.java
Labels: JDBC, enhancement

#1158 tests: Correctly determine if the localhost is in the cluster node list.
  tests/basic.test/runit
Labels: bug

#1186 cdb2jdbc: Better handling of EOF from pmux.
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/DatabaseDiscovery.java
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/Driver.java
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/SockIO.java
Labels: JDBC, bug
