Repository bloomberg/comdb2, pull requests merged in 2018-06, with the labels that each got.

#893 Docker test
  tests/docker/Dockerfile.db
  tests/docker/Dockerfile.install
  tests/docker/client
  tests/docker/common/.empty
  tests/docker/runit
  tests/docker/server
Labels: enhancement

#917 Bump the temptable limit for tmptbl_starve.
  tests/tmptbl_starve.test/lrl.options
Labels: cleanup

#919 Change writes_remsql_names to use bash.
  tests/writes_remsql_names.test/runit
  tests/writes_remsql_names.test/writes_remsql_names.sh
Labels: cleanup

#928 Fix cdb2api READ_INTRANS_RESULTS mode.
  bdb/bdb_api.h
  bdb/bdb_osqltrn.c
  bdb/bdb_osqltrn.h
  bdb/tran.c
  cdb2api/cdb2api.c
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/Comdb2Handle.java
  db/comdb2.h
  db/glue.c
  db/sql.h
  db/sqlglue.c
  db/sqlinterfaces.c
  docs/pages/programming/client_protocol.md
  plugin/newsql/newsql.c
  protobuf/sqlquery.proto
  protobuf/sqlresponse.proto
  tests/cdb2api.test/t36.expected
  tests/cdb2api.test/t36.req
  tests/cdb2api.test/t39.expected
  tests/cdb2api.test/t39.req
  tests/read_intrans_results.test/Makefile
  tests/read_intrans_results.test/runit
  tests/tools/CMakeLists.txt
  tests/tools/cdb2api_read_intrans_results.c
Labels: bug

#924 Remove libreadline6 from Dockerfiles.
  contrib/docker/Dockerfile.build
  contrib/docker/Dockerfile.standalone
  docs/pages/overview/install.md
  tests/docker/Dockerfile.install
  tests/netloss.test/Dockerfile.dev
  tests/smoketest/Dockerfile.deb.build
Labels: cleanup

#954 cdb2api: Fix "SET SSL_MODE VERIFY_DBNAME".
  cdb2api/cdb2api.c
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/Comdb2Handle.java
  tests/ssl_set_cmd.test/output.expected
  tests/ssl_set_cmd.test/runit
Labels: bug

#956 Fix Solaris build.
  bdb/bdblock.c
Labels: bug

#943 cdb2jdbc: client info.
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/Cdb2Query.java
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/Comdb2ClientInfo.java
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/Comdb2Connection.java
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/Comdb2Handle.java
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/DatabaseDiscovery.java
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/Driver.java
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/ProtobufProtocol.java
  cdb2jdbc/src/test/java/com/bloomberg/comdb2/jdbc/ClientInfoTest.java
Labels: JDBC, enhancement
