Repository bloomberg/comdb2, pull requests merged in 2018-08, with the labels that each got.

#1010 Tweak cdb2jdbc timeout test.
  cdb2jdbc/src/test/java/com/bloomberg/comdb2/jdbc/TimeoutTest.java
Labels: JDBC, bug

#1035 metrics: Fix a typo.
  db/sqlinterfaces.c
Labels: bug

#1032 Feature: Decouple installation and data locations
  CMakeLists.txt
Labels: enhancement

#1028 sqlite: Dynamically adjust periodical sampling frequency.
  sqlite/analyze.c
  tests/analyze_insert_burst.test/Makefile
  tests/analyze_insert_burst.test/runit
Labels: bug

#1031 bdb: Change summarize and temptable counters to unsigned long long.
  bdb/summarize.c
  bdb/temptable.c
Labels: bug

#1043 tests: Remove misleading comments from logarchive test.
  tests/logarchive.test/runit
Labels: cleanup

#1047 berkdb: Fix an integer wraparound.
  berkdb/btree/bt_verify.c
Labels: bug

#1049 dlmalloc: Fix memory auto-trimming.
  dlmalloc/dlmalloc.c
Labels: bug

#1021 Docs: Update bubble diagrams related to upsert
  docs/images/insert-stmt.gif
  docs/images/replace-stmt.gif
  docs/images/upsert-clause.gif
  docs/pages/programming/sql.md
  docs/src/sqlitegen/bubble-generator-data.tcl
Labels: docs

#1069 schemachange: Don't double close an SBUF object.
  schemachange/sc_logic.c
  schemachange/sc_struct.c
Labels: bug

#1073 berkdb: Update page generation on the correct variable.
  berkdb/btree/bt_split.c
Labels: bug

#1067 Memory tracker.
  db/process_message.c
  db/repl_wait.c
  dlmalloc/dlmalloc.c
  dlmalloc/dlmalloc.h
  mem/mem.c
  mem/mem.h
  tests/mem_tracker.test/Makefile
  tests/mem_tracker.test/runit
Labels: enhancement
