Repository bloomberg/comdb2, pull requests merged in 2018-04, with the labels that each got.

#788 berkdb: log_archive returns wrong files.
  berkdb/env/env_recover.c
  berkdb/log/log_archive.c
  tests/logarchive.test/Makefile
  tests/logarchive.test/lrl.options
  tests/logarchive.test/runit
Labels: bug

#800 Fix smoke test.
  cdb2api/cdb2api.c
  db/fdb_fend.c
  db/sqlglue.c
  plugin/newsql/newsql.c
  tests/smoketest/Dockerfile.deb.build
  tests/smoketest/Dockerfile.inst.build
  tests/smoketest/Dockerfile.nossl.build
  tests/smoketest/Dockerfile.rpm.build
Labels: bug

#814 Add malloc_resize() to efficiently resize a memory block.
  dlmalloc/dlmalloc.c
  dlmalloc/dlmalloc.h
  mem/mem.c
  mem/mem.h
  mem/mem.h.in
  mem/mem_override.h
  mem/mem_restore.h
  plugin/newsql/newsql.c
  tests/mallocresize.test/Makefile
  tests/mallocresize.test/lrl.options
  tests/mallocresize.test/runit
  tests/tools/CMakeLists.txt
  tests/tools/malloc_resize_test.c
Labels: enhancement

#815 cdb2jdbc: Fix SKIP_ROWS feature test.
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/Comdb2Handle.java
Labels: bug

#810 berkdb: log deletion should take rep_verify_match into account.
  berkdb/env/env_recover.c
  berkdb/log/log.c
  berkdb/log/log_archive.c
  berkdb/rep/rep_record.c
  tests/logarchive.test/lrl.options
  tests/logarchive.test/runit
Labels: bug

#820 berkdb: Handle race condition between __log_find() and log deletion.
  berkdb/log/log.c
Labels: bug

#821 Fix build for macOS
  bb/ssl_io.c
Labels: bug

#823 cdb2jdbc: Refactor Driver.connect().
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/Driver.java
Labels: cleanup
