Repository bloomberg/comdb2, pull requests merged in 2019-01, with the labels that each got.

#1353 Documentation: Fixed Typo s/user/use/
  docs/pages/overview/install.md
Labels: docs

#1347 pthread_mutex_timedlock expects an absolute time.
  db/fdb_fend.c
Labels: bug

#1349 berkdb: Grow fileid track array exponentially.
  berkdb/dbreg/dbreg_rec.c
Labels: enhancement

#1351 Docs: Fix broken links
  docs/pages/programming/c_api.md
Labels: docs

#1352 comdb2ar: back up and restore SSL certificates.
  bbinc/ssl_support.h
  db/comdb2.c
  tests/ssl_comdb2ar.test/Makefile
  tests/ssl_comdb2ar.test/lrl.options
  tests/ssl_comdb2ar.test/runit
  tools/comdb2ar/deserialise.cpp
  tools/comdb2ar/serialise.cpp
Labels: enhancement

#1343 Treat warnings as errors
  CMakeLists.txt
  bdb/CMakeLists.txt
  bdb/bdb_net.c
  bdb/file.c
  berkdb/CMakeLists.txt
  berkdb/btree/bt_pgcompact.c
  berkdb/btree/bt_split.c
  berkdb/db/db_meta.c
  berkdb/dbreg/dbreg.c
  berkdb/fileops/fop_basic.c
  berkdb/lock/lock_deadlock.c
  berkdb/qam/qam.c
  berkdb/rep/rep_method.c
  berkdb/rep/rep_record.c
  berkdb/txn/txn.c
  berkdb/txn/txn_auto.c
  cdb2api/cdb2api.c
  crc32c/crc32c.c
  cson/CMakeLists.txt
  datetime/CMakeLists.txt
  db/db_metrics.c
  db/plugin_handler.c
  db/reqlog.c
  db/sqlglue.c
  db/testcompr.c
  db/types.c
  db/watchdog.c
  dlmalloc/CMakeLists.txt
  lua/ltablib.c
  net/net.c
  sqlite/CMakeLists.txt
  tcl/tclcdb2.c
  tests/cdb2api_unit.test/Makefile
  tests/tools/api_events.c
  tests/tools/breakloop.c
  tests/tools/crle.c
  tests/tools/hatest.c
  tests/tools/md5.c
  tests/tools/nemesis.c
  tests/tools/sqllogictest.c
  tests/tools/stepper.c
  tools/cdb2_dump/cdb2_dump.c
  tools/cdb2_printlog/cdb2_printlog.c
  tools/cdb2_stat/cdb2_stat.c
  tools/cdb2_verify/cdb2_verify.c
  tools/cdb2sockpool/cdb2sockpool.c
  tools/cdb2sql/cdb2sql.cpp
  tools/comdb2ar/deserialise.cpp
  tools/comdb2ar/incr_deserialise.cpp
  tools/comdb2ar/increment.cpp
  tools/comdb2ar/repopnewlrl.cpp
  tools/comdb2ar/serialise.cpp
  tools/comdb2ar/util.cpp
  tools/pmux/pmux.cpp
  util/sbuf2.c
  util/ssl_support.c
Labels: SQLite

#1357 newsql: Handle "SET REMOTE" failure correctly.
  plugins/newsql/newsql.c
  tests/simple_remsql.test/t8_13.req.out
  tests/simple_remsql.test/t8_13.req.src
Labels: bug

#1363 fix remote sql version 0 issue
  db/fdb_fend.c
  db/sqlglue.c
  sqlite/src/build.c
  sqlite/src/prepare.c
Labels: SQLite

#1367 Add tunable to enable use of the PRAGMA SQL command.
  db/comdb2.c
  db/db_tunables.c
  db/db_tunables.h
  db/sqlinterfaces.c
Labels: enhancement, ready to review

#1369 sqlite: Fix tokenizer to treat LZ4 as a keyword
  sqlite/src/tokenize.c
  tests/ddl_no_csc2.test/t00_create_table.expected
  tests/ddl_no_csc2.test/t00_create_table.sql
Labels: SQLite

#1391 Fix get_next_addrem_buffer() abort for data items smaller than genid size.
  bdb/bdb_osqllog.c
  schemachange/sc_records.c
  sqlite/ext/comdb2/logicalops.c
  tests/snapisol.test/t9.runstepper
  tests/snapisol.test/t9_01.req
  tests/snapisol.test/t9_01.req.exp
Labels: bug

#1368 Add tunable to run SQL command(s) for each new connection.
  bbinc/segstring.h
  bbinc/tunables.h
  db/comdb2.c
  db/db_tunables.c
  db/db_tunables.h
  db/sqlinterfaces.c
  sqlite/ext/comdb2/tunables.c
  tests/tunables.test/lrl.options
  tests/tunables.test/t02_sqlite_rc_tunable.expected
  tests/tunables.test/t02_sqlite_rc_tunable.sql
  util/segstring.c
Labels: enhancement, ready to review

#1389 sqlglue: Remove useless code.
  db/sqlglue.c
Labels: cleanup

#1390 Fix empty blob handling for logical-op-redo schema change.
  bdb/odh.c
  schemachange/sc_records.c
  tests/logical_sc_empty_blob.test/Makefile
  tests/logical_sc_empty_blob.test/runit
Labels: bug

#1392 Merge upstream updates from the SQLite 3.26 branch...
  sqlite/definitions.cmake
  sqlite/src/alter.c
  sqlite/src/analyze.c
  sqlite/src/expr.c
  sqlite/src/func.c
  sqlite/src/os_unix.c
  sqlite/src/select.c
  sqlite/src/sqlite3.h
  sqlite/src/upsert.c
  sqlite/src/where.c
  sqlite/src/window.c
  tests/cdb2api.test/t23.expected
  tests/limitsortingtbl.test/sel1.expected
  tests/yast.test/index6.test
  tests/yast.test/indexexpr1.test
  tests/yast.test/orderby1.test
  tests/yast.test/orderby5.test
  tests/yast.test/where3.test
Labels: R7, SQLite, ready to review

#1394 Fix verify for the blob2 type (i.e. inline blob).
  db/verify.c
  tests/blob2.test/lrl.options
  tests/blob2.test/t02.expected
  tests/blob2.test/t02.req
  tests/blob2.test/t2.csc2
Labels: bug

#1400 SSL: don't use a singleton memory allocator.
  db/ssl_bend.c
  tests/simple_ssl.test/runit
Labels: bug

#1410 autoanalyze request mode
  bdb/attr.h
  db/autoanalyze.c
  tests/tunables.test/t00_all_tunables.expected
Labels: enhancement

#1419 Fix pthread_mutex_lock EINVAL abort in clean_queries_not_cached_in_srs().
  db/sqlglue.c
  db/sqlinterfaces.c
  tests/socksql.test/t1_04.req
  tests/socksql.test/t1_04.req.exp
Labels: bug
