Repository bloomberg/comdb2, pull requests merged in 2019-09, with the labels that each got.

#1795 csc2: Simplify the GC logic
  csc2/CMakeLists.txt
  csc2/macc.h
  csc2/macc_so.c
  csc2/macclex.l
  mem/mem.h
Labels: cleanup

#1786 The sqlite3_value_dup_inplace() function must zero szMalloc.
  sqlite/src/vdbeInt.h
  sqlite/src/vdbeapi.c
  sqlite/src/vdbeaux.c
Labels: R7, bug, port to release, ready to review

#1793 Fix a race between time partition rollout and regular schema change
  csc2/macc_so.c
  db/osqlblockproc.c
  db/views.c
  schemachange/sc_logic.c
Labels: R7, bug

#1799 Add 'strict_double_quotes' tunable to forbid use of double-quoted string literals
  db/comdb2.c
  db/comdb2.h
  db/db_tunables.h
  sqlite/src/resolve.c
  tests/strict_dbl_quotes.test/Makefile
  tests/strict_dbl_quotes.test/README
  tests/strict_dbl_quotes.test/lrl.options
  tests/strict_dbl_quotes.test/runit
  tests/strict_dbl_quotes.test/strict.sh
  tests/strict_dbl_quotes.test/t01.req
  tests/strict_dbl_quotes.test/t01.req.out
  tests/strict_dbl_quotes.test/t02.req
  tests/strict_dbl_quotes.test/t02.req.args
  tests/strict_dbl_quotes.test/t02.req.out
  tests/strict_dbl_quotes.test/t02.req.tool
  tests/strict_dbl_quotes.test/t03.req
  tests/strict_dbl_quotes.test/t03.req.out
  tests/strict_dbl_quotes.test/test.sh
Labels: R7, SQLite, enhancement, ready to review

#1807 Disable the warning trace message when the authorizer hits a PRAGMA
  db/sqlinterfaces.c
Labels: R7, enhancement, ready to review

#1755 Allow unquoted composite tunable names in PUT TUNABLE command
  docs/images/put.gif
  docs/src/sqlitegen/bubble-generator-data.tcl
  sqlite/src/comdb2build.c
  sqlite/src/comdb2build.h
  sqlite/src/parse.y
  tests/tunables.test/t01_dyn_tunables.expected
  tests/tunables.test/t01_dyn_tunables.sql
Labels: SQLite

#1817 Cleanup handling of the 'persistent_info' used by the thread pool
  util/thdpool.c
Labels: cleanup, ready to review

#1819 Detect and reject use of BEGIN, COMMIT, ROLLBACK, SAVEPOINT, and RELEASE through the SQLite parser
  sqlite/src/parse.y
  tests/sp_sql_tran.test/Makefile
  tests/sp_sql_tran.test/runit
  tests/sp_sql_tran.test/sp_sql_tran.sh
  tests/sp_sql_tran.test/t01.req
  tests/sp_sql_tran.test/t01.req.args
  tests/sp_sql_tran.test/t01.req.out
  tests/sp_sql_tran.test/t01.req.tool
  tests/sp_sql_tran.test/test.sh
Labels: SQLite, bug, ready to review
