Repository bloomberg/comdb2, pull requests merged in 2019-11, with the labels that each got.

#1897 Fix use of comdb2_rowid in WHERE clauses (backport)
  db/sqlglue.c
  sqlite/src/sqlite_btree.h
  sqlite/src/vdbe.c
  tests/basic.test/runit
Labels: R7, bug, ready to review

#1885 Remove a superfluous use of calloc in the Lua stored procedure subsystem.
  lua/sp.c
Labels: R7, enhancement, ready to review

#1912 Maximum row buffer size
  db/db_tunables.c
  db/db_tunables.h
  plugins/newsql/newsql.c
  tests/row_buf_max_sz.test/Makefile
  tests/row_buf_max_sz.test/lrl.options
  tests/row_buf_max_sz.test/runit
  tests/tunables.test/t00_all_tunables.expected
Labels: enhancement

#1809 Auth: A special commandline option to bypass access checks
  bdb/llmeta.c
  db/comdb2.c
  db/config.c
Labels: PORT TO 7.0

#1821 reqlog: cnonce might not be a valid utf-8 string
  db/eventlog.c
Labels: PORT TO 7.0

#1834 logmsg: Introduce 'logmsg.skiplevel' to skip attaching level to the log message
  db/config.c
  db/db_tunables.h
  docs/pages/config/config_files.md
  util/logmsg.c
  util/logmsg.h
Labels: PORT TO 7.0

#1920 Fix smoke test for CentOS 8
  README.md
  tests/smoketest/Dockerfile.inst.build
  tests/smoketest/Dockerfile.nossl.build
  tests/smoketest/Dockerfile.rpm.build
Labels: testsuite

#1921 Make the memdup diagnostic APIs slightly easier to use.
  bbinc/memdup.h
  util/memdup.c
Labels: enhancement

#1924 Make the result of sqlite3_normalized_sql() survive its statement being reprepared.
  sqlite/src/vdbeaux.c
Labels: PORT TO 7.0, Port_To_R6, R7, SQLite, ready to review

#1917 Add experimental SQL function to return qualified table names referenced by an arbitrary SELECT statement
  sqlite/src/comdb2build.c
  sqlite/src/func.c
  sqlite/src/prepare.c
  sqlite/src/select.c
  sqlite/src/sqlite.h.in
  sqlite/src/sqlite3.h
  sqlite/src/sqliteInt.h
  sqlite/src/tokenize.c
  sqlite/src/vdbe.h
  tests/sql.test/t9_01.req
  tests/sql.test/t9_01.req.exp
Labels: PORT TO 7.0, Port_To_R6, R7, SQLite, WIP, enhancement

#1925 Make the result of sqlite3_normalized_sql() survive its statement being reprepared (backport).
  sqlite/src/vdbeaux.c
Labels: R7, SQLite, bug, port, ready to review

#1926 Before placing a prepared statement back into the cache, clear its parameter bindings. Also, detect and log related errors.
  db/sqlinterfaces.c
Labels: bug

#1896 Fix use of comdb2_rowid in WHERE clauses
  db/sqlglue.c
  sqlite/src/sqlite_btree.h
  sqlite/src/vdbe.c
  tests/basic.test/runit
Labels: R7, SQLite, bug, ready to review

#1929 Fix unportable usage of realpath
  bbinc/bb_oscompat.h
  db/comdb2.c
  db/resource.c
  lua/sp.c
  util/bb_oscompat.c
Labels: bug

#1927 Carefully adjust thd->persistent_info at strategic points in the pool thread lifecycle to more closely reflect what it is actually doing.
  util/thdpool.c
Labels: enhancement, ready to review

#1930 Simpler and faster GENID48 generation
  bdb/bdb_int.h
  bdb/file.c
  bdb/genid.c
  bdb/info.c
  bdb/llmeta.c
Labels: enhancement

#1943 Fix repopulating a queuedb
  db/comdb2.c
  db/config.c
  db/db_tunables.c
  db/db_tunables.h
  tests/repopulate_queues.test/Makefile
  tests/repopulate_queues.test/runit
  tests/tunables.test/t00_all_tunables.expected
Labels: R7, bug

#1935 Free the path returned by realpath in the create_db function.
  db/comdb2.c
Labels: bug, ready to review

#1937 Remove superfluous (duplicated) block of code.
  sqlite/src/comdb2build.c
Labels: cleanup, ready to review
