Repository bloomberg/comdb2, pull requests merged in 2019-08, with the labels that each got.

#1742 cdb2api: Add BEFORE_DISCOVERY and AFTER_DISCOVERY events
  cdb2api/cdb2api.c
  cdb2api/cdb2api.h
  docs/pages/programming/c_api.md
Labels: enhancement

#1739 Remove some dead code.
  db/glue.c
Labels: R7, cleanup, ready to review

#1673 Refactoring work in preparation for prioritizing SQL query work items
  db/db_fingerprint.c
  db/dohsql.c
  db/fdb_bend_sql.c
  db/osql_srs.c
  db/osqlsqlthr.c
  db/sql.h
  db/sqlanalyze.c
  db/sqlexplain.c
  db/sqlglue.c
  db/sqlinterfaces.c
  db/sqloffload.c
  lua/sp.c
  plugins/newsql/newsql.c
  sqlite/src/main.c
Labels: R7, cleanup, ready to review, refactor

#1757 comdb2_user() function
  db/sql.h
  db/sqlinterfaces.c
  docs/pages/programming/sql.md
  sqlite/src/func.c
  tests/auth.test/t00.expected
  tests/auth.test/t00.req
  tests/auth.test/t01.expected
  tests/auth.test/t01.req
  tests/auth.test/t02.expected
  tests/auth.test/t02.req
  tests/auth.test/t03.expected
  tests/auth.test/t03.req
  tests/union_parallel.test/9_2_params.req
  tests/union_parallel.test/9_2_params.req.exp
Labels: SQLite

#1753 Log clnt stats
  cdb2api/cdb2api.c
  db/comdb2.c
  db/comdb2.h
  db/db_fingerprint.c
  db/reqlog.c
  db/sql.h
  db/sqlinterfaces.c
  lua/sp.c
  sqlite/CMakeLists.txt
  sqlite/ext/comdb2/comdb2systblInt.h
  sqlite/ext/comdb2/ezsystables.c
  sqlite/ext/comdb2/fingerprints.c
  sqlite/ext/comdb2/sqlclientstats.c
  sqlite/ext/comdb2/tables.c
  tests/auth.test/t09.expected
  tests/cdb2sql.test/t00.expected
  tests/comdb2sys.test/comdb2sys.expected
  tests/comdb2sys.test/runit
  tests/comdb2sys.test/testclients.expected
  tests/comdb2sys.test/testsqlclients
  tests/fingerprints.test/t03.req
  tests/fingerprints.test/t03.req.out
  tests/svc_time_per_clnt.test/Makefile
  tests/svc_time_per_clnt.test/runit
  tests/userschema.test/t00.expected
  tests/userschema.test/t07.expected
  tests/userschema.test/t09.expected
Labels: SQLite

#1779 Fix compiler warnings related to memory debugging
  db/sqlinterfaces.c
Labels: R7, bug, ready to review
