Repository bloomberg/comdb2, pull requests merged in 2019-10, with the labels that each got.

#1840 cdb2jdbc: Fix PreparedStatement.setNull()
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/Comdb2PreparedStatement.java
  cdb2jdbc/src/test/java/com/bloomberg/comdb2/jdbc/PreparedStatementTest.java
Labels: JDBC

#1839 Small doc fixes
  docs/images/drop.gif
  docs/images/set-stmt.gif
  docs/src/sqlitegen/bubble-generator-data.tcl
Labels: R7, bug, docs, ready to review

#1833 logmsg: Update log message to match with one in r6
  plugins/dbqueuedb/dbqueuedb.c
Labels: PORT TO 7.0

#1844 Fix DOHSQL memory leak
  sqlite/src/vdbeaux.c
  tests/dohsql_leaks.test/Makefile
  tests/dohsql_leaks.test/lrl.options
  tests/dohsql_leaks.test/runit
Labels: R7, SQLite, bug

#1848 Fix a memory leak in the procedures system table
  sqlite/ext/comdb2/procedures.c
  tests/systbl_proc_leak.test/Makefile
  tests/systbl_proc_leak.test/runit
Labels: R7, SQLite, bug

#1829 Add 'include_defaults' directive to the cdb2api configuration file subsystem.
  cdb2api/cdb2api.c
  tcl/tclcdb2.c
  tcl/tests/tclcdb2.test
Labels: R7, enhancement, ready to review

#1826 Restore the WITH_TCL option for CMake; making sure it is OFF by default
  CMakeLists.txt
Labels: R7, bug, ready to review

#1863 Disable a SQLite assert that does not apply to Comdb2
  sqlite/src/vdbe.c
Labels: R7, SQLite, bug, ready to review

#1869 Traps for the fingerprint subsystem...
  db/config.c
  db/db_fingerprint.c
  db/process_message.c
  db/sql.h
Labels: R7, enhancement, ready to review

#1831 Early verify in update with limit
  db/sqlglue.c
  sqlite/src/delete.c
  sqlite/src/wherecode.c
  tests/early_verify.test/Makefile
  tests/early_verify.test/actions.csc2
  tests/early_verify.test/expected.out
  tests/early_verify.test/lrl.options
  tests/early_verify.test/runit
Labels: SQLite

#1806 cdb2jdbc: Cursor position
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/Comdb2Handle.java
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/Comdb2ResultSet.java
  cdb2jdbc/src/test/java/com/bloomberg/comdb2/jdbc/CursorStateTest.java
Labels: JDBC

#1871 cdb2jdbc: Fix Connection.setTransactionIsolation() when autoCommit is on
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/Comdb2Handle.java
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/Comdb2Statement.java
  cdb2jdbc/src/test/java/com/bloomberg/comdb2/jdbc/ConnectionTest.java
Labels: JDBC

#1876 Fix SQL mspace race condition in DOHSQL
  db/dohsql.c
  db/sqlinterfaces.c
  sqlite/src/main.c
  sqlite/src/prepare.c
  tests/dohsql_race.test/Makefile
  tests/dohsql_race.test/lrl.options
  tests/dohsql_race.test/runit
Labels: R7, bug, cleanup

#1874 Make window functions work
  bdb/temptable.c
  tests/window.test/Makefile
  tests/window.test/README
  tests/window.test/lrl.options
  tests/window.test/runit
  tests/window.test/t00.expected
  tests/window.test/t00.sql
Labels: PORT TO 7.0

#1889 Traps for the fingerprint subsystem... (backport of #1869)
  db/config.c
  db/db_fingerprint.c
  db/process_message.c
  db/sql.h
Labels: R7, enhancement, ready to review

#1901 sql_tranlevel: Change level only for valid modes
  db/config.c
  db/db_tunables.c
  db/sqlinterfaces.c
Labels: PORT TO 7.0

#1902 Fix DOHAST double-free
  db/dohast.c
  tests/dohsql_leaks.test/runit
Labels: R7, bug
