Repository bloomberg/comdb2, pull requests merged in 2019-07, with the labels that each got.

#1659 Fix an incorrect usage of pthread_mutex_lock / pthread_mutex_unlock...
  schemachange/sc_logic.c
  schemachange/sc_struct.c
  schemachange/schemachange.c
  schemachange/schemachange.h
Labels: R7, bug

#1666 Add --version (v) command line argument and comdb2_sysinfo('version')
  db/CMakeLists.txt
  db/comdb2.c
  db/comdb2.h
  db/config.c
  db/config.h
  sqlite/src/func.c
Labels: R7, SQLite

#1665 Fix dohsql orderby multiple
  db/dohast.c
  db/dohsql.c
  sqlite/src/expr.c
  tests/union_parallel.test/5_1_order.req
  tests/union_parallel.test/5_1_order.req.exp
Labels: R7, SQLite

#1672 fix increment keyword
  sqlite/src/parse.y
Labels: R7, SQLite

#1676 Fix an inconsistency in the use of SQLITE_BUILDING_FOR_COMDB2.
  sqlite/src/analyze.c
Labels: R7, SQLite, bug

#1532 CHECK constraint
  cdb2api/cdb2api.h
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/Comdb2Connection.java
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/Constants.java
  csc2/dynschemaload.h
  csc2/macc.h
  csc2/macc_so.c
  csc2/maccglobals.c
  csc2/macclex.l
  csc2/maccparse.y
  db/comdb2.c
  db/comdb2.h
  db/config.c
  db/constraints.c
  db/record.c
  db/sqlconstraints.h
  db/sqlglue.c
  db/sqlinterfaces.c
  db/tag.c
  db/views.c
  docs/images/column-constraint.gif
  docs/images/constraint-section.gif
  docs/images/table-constraint.gif
  docs/pages/programming/c_api.md
  docs/src/sqlitegen/bubble-generator-data.tcl
  lua/sp.c
  schemachange/sc_add_table.c
  schemachange/sc_alter_table.c
  schemachange/sc_fastinit_table.c
  schemachange/sc_records.c
  schemachange/sc_schema.c
  schemachange/sc_struct.c
  schemachange/schemachange.c
  sqlite/ext/comdb2/constraints.c
  sqlite/src/comdb2build.c
  sqlite/src/comdb2build.h
  sqlite/src/parse.y
  tests/cdb2sql.test/t00.expected
  tests/comdb2sys.test/comdb2sys.expected
  tests/ddl_no_csc2.test/runit
  tests/ddl_no_csc2.test/t00_create_table.expected
  tests/ddl_no_csc2.test/t01_alter_table.expected
  tests/ddl_no_csc2.test/t09_check.expected
  tests/ddl_no_csc2.test/t09_check.sql
  tests/upsert.test/t00_upsert.expected
  tests/upsert.test/t00_upsert.sql
  tests/yast.test/check.test
  tests/yast.test/tester.tcl
Labels: SQLite

#1677 Add comdb2_sysinfo('tid')
  sqlite/src/func.c
Labels: R7, SQLite, enhancement

#1682 Track and report SQL query preparation time for use with fingerprints
  db/db_fingerprint.c
  db/sql.h
  db/sqlinterfaces.c
  sqlite/ext/comdb2/fingerprints.c
Labels: R7, WIP, enhancement

#1691 Create comdb2_ctxinfo() SQL function and move the 'parallel' named scalar to it.
  db/dohast.c
  sqlite/ext/misc/completion.c
  sqlite/src/func.c
  tests/auth.test/t09.expected
  tests/union_parallel.test/9_2_params.req
  tests/union_parallel.test/9_2_params.req.exp
Labels: R7, SQLite, enhancement

#1689 berkdb: Throttle REP_LOG messages.
  berkdb/rep/rep_record.c
  berkdb/rep/rep_util.c
  net/net.c
Labels: R7, bug, help wanted

#1694 [7.0] berkdb: Throttle REP_LOG messages
  berkdb/rep/rep_record.c
  berkdb/rep/rep_util.c
  net/net.c
Labels: R7, port

#1693 Add a verify callback for the 'dtastripe' tunable parameter.
  bbinc/tunables.h
  bdb/attr.h
  db/db_tunables.c
  db/db_tunables.h
Labels: R7, enhancement, ready to review

#1670 Minor refactoring / enhancements in the thread pool subsystem.
  util/thdpool.c
Labels: R7, ready to review, refactor

#1698 Having sql_tick always recover deadlock when bdb lock is desired.
  db/sqlglue.c
  tests/recover_deadlock.test/runit
Labels: R7, bug

#1652 Faster Analyze
  bdb/bdb_api.h
  bdb/summarize.c
  db/analyze.h
  db/sql.h
  db/sqlanalyze.c
  db/sqlglue.c
  tests/analyze_sample.test/Makefile
  tests/analyze_sample.test/lrl.options
  tests/analyze_sample.test/runit
  tests/analyze_sample.test/stat4.expected
Labels: enhancement, ready to review

#1700 [7.0] Having sql_tick always recover deadlock when bdb lock is desired
  db/sqlglue.c
  tests/recover_deadlock.test/runit
Labels: R7, port

#1701 Fix a memory leak in shadow table blob handling
  db/osqlshadtbl.c
Labels: bug

#1702 [7.0] Fix a memory leak in shadow table blob handling
  db/osqlshadtbl.c
Labels: R7, port

#1533 Support for VIEWs
  bdb/bdb_api.h
  bdb/bdb_schemachange.h
  bdb/llmeta.c
  db/comdb2.c
  db/comdb2.h
  db/osqlcomm.c
  db/sql.h
  db/sqlglue.c
  db/sqlmaster.c
  db/views_sqlite.c
  docs/images/create-view.gif
  docs/images/drop.gif
  docs/pages/programming/sql.md
  docs/pages/programming/system_tables.md
  docs/src/sqlitegen/bubble-generator-data.tcl
  schemachange/CMakeLists.txt
  schemachange/sc_callbacks.c
  schemachange/sc_logic.c
  schemachange/sc_struct.c
  schemachange/sc_view.c
  schemachange/sc_view.h
  schemachange/schemachange.h
  sqlite/CMakeLists.txt
  sqlite/ext/comdb2/comdb2systblInt.h
  sqlite/ext/comdb2/tables.c
  sqlite/ext/comdb2/views.c
  sqlite/src/build.c
  sqlite/src/comdb2build.c
  sqlite/src/parse.y
  sqlite/src/select.c
  sqlite/src/sqliteInt.h
  tests/auth.test/t09.expected
  tests/cdb2sql.test/t00.expected
  tests/comdb2sys.test/comdb2sys.expected
  tests/ddl_no_csc2.test/t00_create_table.expected
  tests/ddl_no_csc2.test/t00_create_table.sql
  tests/ddl_no_csc2.test/t01_alter_table.expected
  tests/ddl_no_csc2.test/t01_alter_table.sql
  tests/ddl_no_csc2.test/t04_create_like.sql
  tests/ddl_no_csc2.test/t08_view.expected
  tests/ddl_no_csc2.test/t08_view.sql
  tests/ddl_no_csc2.test/t09_check.expected
  tests/ddl_no_csc2.test/t09_check.sql
  tests/userschema.test/t00.expected
  tests/userschema.test/t07.expected
  tests/userschema.test/t09.expected
  tests/yast.test/delete1.test
  tests/yast.test/tester.tcl
  tests/yast.test/view.test
  tools/cdb2sql/cdb2sql.cpp
Labels: SQLite

#1696 Cleanup usage of counters in the sql_thread struct
  db/sql.h
  db/sqlglue.c
  db/sqlinterfaces.c
Labels: R7, ready to review, refactor

#1649 watcher_thread: Warn of long log truncation
  bdb/rep.c
  db/db_tunables.c
  db/db_tunables.h
  tests/grace_period_on_exit.test/Makefile
  tests/grace_period_on_exit.test/runit
Labels: R7, cleanup

#1710 Sync up with 'branch-3.28' of SQLite from upstream and make styling consistent.
  sqlite/ext/comdb2/tables.c
  sqlite/ext/comdb2/views.c
  sqlite/src/build.c
  sqlite/src/comdb2build.c
Labels: R7, SQLite, cleanup, ready to review

#1731 Fix spurious failures in the 'sp' test caused by the (pending) creation of a time partition during subsequent SQL statement preparation.
  tests/sp.test/sp.sh
  tests/sp.test/t01.req.out
Labels: R7, bug, ready to review, testsuite

#1724 Make sure that a queue work item timeout is handled for the SQL engine thread pool.
  db/db_tunables.c
  db/db_tunables.h
  db/sqlinterfaces.c
  tests/sp_timeout.test/Makefile
  tests/sp_timeout.test/lrl.options
  tests/sp_timeout.test/runit
  tests/sp_timeout.test/sp_timeout.sh
  tests/sp_timeout.test/t01.req
  tests/sp_timeout.test/t01.req.args
  tests/sp_timeout.test/t01.req.tool
  tests/sp_timeout.test/test.sh
  util/thdpool.c
Labels: R7, bug, ready to review

#1708 Make use of sqlite3_maybe_step() from within the SP subsystem.
  lua/sp.c
Labels: R7, enhancement, ready to review

#1717 Fix a use of uninitialized bytes as reported by valgrind.
  sqlite/ext/comdb2/procedures.c
Labels: R7, cleanup, ready to review

#1716 Fix a mutex/memory leak if sqlite3_step() fails in create_temp_table().
  db/sqlglue.c
  lua/sp.c
Labels: R7, bug

#1730 Fix analyze abort crash.
  bdb/summarize.c
  db/sqlglue.c
  tests/analyze_sample.test/runit
Labels: bug

#1740 Fix segfault when performing an arithmetic operation on NULL and DECIMAL operands
  sqlite/src/vdbe.c
  sqlite/src/vdbemem.c
  tests/sql.test/t8_01.req
  tests/sql.test/t8_01.req.exp
Labels: R7, SQLite, bug, ready to review
