Repository bloomberg/comdb2, pull requests merged in 2019-02, with the labels that each got.

#1421 PORTED: IS_ZERO_LSN should check (file == 0 && offset == 0)
  berkdb/build/db_int.h
Labels: bug

#1412 more system tables and refactored cron schedulers
  bdb/attr.h
  db/CMakeLists.txt
  db/comdb2.c
  db/cron.c
  db/cron.h
  db/cron_systable.h
  db/logical_cron.c
  db/logical_cron.h
  db/osqlcomm.c
  db/timepart_systable.h
  db/views.c
  db/views.h
  db/views_cron.c
  db/views_cron.h
  db/views_serial.c
  db/views_systable.c
  docs/pages/programming/system_tables.md
  plugins/dbqueuedb/dbqueuedb.c
  sqlite/CMakeLists.txt
  sqlite/ext/comdb2/comdb2systblInt.h
  sqlite/ext/comdb2/crons.c
  sqlite/ext/comdb2/tables.c
  sqlite/ext/comdb2/timepartitions.c
  sqlite/src/comdb2build.c
  sqlite/src/comdb2build.h
  sqlite/src/parse.y
  tests/cdb2sql.test/t00.expected
  tests/comdb2sys.test/comdb2sys.expected
  tests/tunables.test/t00_all_tunables.expected
  tests/userschema.test/t00.expected
  tests/userschema.test/t07.expected
  tests/userschema.test/t09.expected
Labels: R7, SQLite, enhancement

#1417 Fix a memory leak in remsql.
  plugins/remsql/fdb_comm.c
Labels: bug, ready to review

#1411 Optimize password authentication.
  bdb/llmeta.c
  db/bpfunc.c
  db/comdb2.h
  db/db_tunables.c
  db/db_tunables.h
  db/glue.c
  db/sql.h
  db/sqlinterfaces.c
  docs/pages/config/config_files.md
  plugins/newsql/newsql.c
  tests/sql.test/t6.runstepper
  tests/sql.test/t6_01.req
  tests/sql.test/t6_01.req.exp
  tests/tunables.test/t00_all_tunables.expected
Labels: enhancement, ready to review

#1395 Docs: System tables
  docs/pages/programming/system_tables.md
Labels: docs

#1399 Send preprocessed blobs to the master.
  bdb/add.c
  bdb/attr.h
  bdb/bdb_api.h
  bdb/bdb_int.h
  bdb/bdb_llops.c
  bdb/ll.c
  bdb/odh.c
  bdb/phys.c
  bdb/upd.c
  db/comdb2.c
  db/comdb2.h
  db/config.c
  db/glue.c
  db/localrep.c
  db/osqlblockproc.c
  db/osqlcomm.c
  db/osqlcomm.h
  db/osqlshadtbl.c
  db/osqlsqlthr.c
  db/record.c
  db/tag.c
  db/types.h
  schemachange/sc_records.c
  schemachange/schemachange.c
  tests/basic.test/off_osql_odh_blob.testopts
  tests/odh_blobs.test/Makefile
  tests/odh_blobs.test/expected
  tests/odh_blobs.test/runit
  tests/odh_blobs.test/t1.csc2
  tests/odh_blobs.test/t2.csc2
  tests/odh_blobs.test/t3.csc2
  tests/sc_add_vutf8.test/off_osql_odh_blob.testopts
  tests/sc_vutf8_blob2.test/off_osql_odh_blob.testopts
  tests/snapblob.test/off_osql_odh_blob.testopts
  tests/tunables.test/t00_all_tunables.expected
  tests/vutf8_dbstore.test/off_osql_odh_blob.testopts
  tests/vutf8_rowlocks.test/off_osql_odh_blob.testopts
Labels: enhancement, ready to review

#1418 Refactor constraint.c and other constrait related files
  db/block_internal.h
  db/comdb2.h
  db/constraints.c
  db/indices.c
  db/record.c
  db/toblock.c
  db/watchdog.c
  tests/docker/Dockerfile.install
Labels: cleanup, refactor

#1432 Parallel sql with params
  db/dohast.c
  db/dohsql.c
  db/dohsql.h
  db/shard_range.h
  db/sqlinterfaces.c
  db/sqlinterfaces.h
  sqlite/src/expr.c
  sqlite/src/sqliteInt.h
  sqlite/src/util.c
  tests/union_parallel.test/9_1_params.req
  tests/union_parallel.test/9_1_params.req.exp
  tools/cdb2sql/cdb2sql.cpp
Labels: R7, SQLite

#1437 Auto fix blob inconsistency.
  bdb/bdb_verify.c
Labels: enhancement

#1211 regexp() user function
  sqlite/CMakeLists.txt
  sqlite/ext/misc/regexp.c
  sqlite/src/main.c
  tests/yast.test/regexp1.test
  tests/yast.test/regexp2.test
Labels: SQLite

#1458 Rebuild our way out of the 0-len blob corruption
  db/toblob.c
Labels: bug

#1378 cdb2api: Uninstall statically linked libraries.
  cdb2api/cdb2api.c
  tests/api_dl_libs.test/expected
  tests/odh_blobs.test/runit
  tests/tools/api_events.c
  tests/tools/api_libs.c
Labels: enhancement

#1420 Fix a couple memory leaks in cdb2api.
  cdb2api/cdb2api.c
Labels: bug, ready to review
