Repository bloomberg/comdb2, pull requests merged in 2019-12, with the labels that each got.

#1965 Track fingerprints for Lua SQL queries where a statement is explicitly closed
  lua/sp.c
  tests/fingerprints.test/fp.sh
  tests/fingerprints.test/t02.req.out
  tests/fingerprints.test/t03.req.out
Labels: PORT TO 7.0, Port_To_R6, R7, bug, ready to review

#1969 Better handling of very long IN lists
  sqlite/src/expr.c
Labels: R7, SQLite, enhancement

#1787 Smartbeat
  cdb2api/cdb2api.c
  cdb2api/cdb2api.h
  db/sql.h
  db/sqlglue.c
  db/sqlinterfaces.c
  lua/sp.c
  plugins/newsql/newsql.c
  sqlite/ext/comdb2/tranlog.c
  tests/smartbeats.test/Makefile
  tests/smartbeats.test/runit
  tests/tools/CMakeLists.txt
  tests/tools/smartbeats.c
Labels: R7, enhancement

#1981 sp: Fix luaL_checknumber
  lua/luautil.c
  tests/sp.test/t09.req
  tests/sp.test/t09.req.out
Labels: PORT TO 7.0, PORT TO R6

#1968 Grab table locks on queue operations
  bdb/llmeta.c
  bdb/queue.c
Labels: PORT TO 7.0

#1991 Micro-optimizations
  bdb/rep.c
  bdb/temptable.c
  berkdb/log/log_put.c
  cdb2api/cdb2api.c
  db/db_fingerprint.c
  db/toblock.c
  util/object_pool.c
Labels: enhancement

#1936 Use consistent error handling and cleanup semantics for c_close and c_get (fix leak-on-error) in the queuedb subsystem.
  bdb/queuedb.c
Labels: PORT TO 7.0, PORT TO R6, bug, ready to review

#1360 Simplify the memory management when searching using bdb_temp_table_find_exact().
  bdb/bdb_osqlcur.c
  bdb/bdb_osqllog.c
  bdb/cursor.c
  bdb/fetch.c
  bdb/temptable.c
  db/osqlshadtbl.c
Labels: cleanup

#2000 Fix omission of 'drop_view' from the 'get_ddl_type_str' schema change function.
  schemachange/sc_logic.c
Labels: R7, bug, ready to review
