Repository bloomberg/comdb2, pull requests merged in 2019-05, with the labels that each got.

#1530 net: Correctly release memory on a pthread_create failure
  net/net.c
Labels: bug

#1544 Fix a double free in VDBE Datetime handling
  sqlite/src/vdbemem.c
  tests/datetime.test/t6_01.req
  tests/datetime.test/t6_01.req.expected
Labels: SQLite, bug

#1545 Fix resizing a LIFO object pool
  tests/objpool.test/Makefile
  tests/objpool.test/runit
  util/object_pool.c
Labels: bug

#1547 net: Fix self-deadlock on a failed write_connect_message.
  net/net.c
Labels: bug

#1521 Temparray
  bdb/bdb_api.h
  bdb/temptable.c
  db/osqlblockproc.c
  db/osqlshadtbl.c
Labels: enhancement, ready to review

#1562 Fix temptable segfault when a trigger attempts to open a temporary btree via SQL
  lua/sp.c
  tests/trigger.test/Makefile
  tests/trigger.test/runit
  tests/trigger.test/t01.expected
  tests/trigger.test/t01.req
Labels: R7, bug

#1529 Add 'host' and 'master' to the comdb2_sysinfo SQL function
  sqlite/src/func.c
Labels: R7, SQLite, enhancement, ready to review

#1560 Fix a race between clean-exit and net queue stat
  bdb/rep_qstat.c
  net/net.c
  net/net.h
Labels: bug

#1564 Cosmetic changes to fix warning from code analysis.
  bdb/bdb_verify.c
  bdb/llmeta.c
  bdb/rowlocks.c
  berkdb/log/log_archive.c
  db/comdb2.h
  db/toblock.c
Labels: cleanup

#1563 Empty blobs shouldn't be bound like NULL
  plugins/newsql/newsql.c
  tests/tools/cdb2bind.c
Labels: bug

#1548 Fixes for SQL identifier and string literal quoting issues
  db/fdb_fend.c
  db/logical_cron.c
  db/sqlanalyze.c
  sqlite/src/build.c
  sqlite/src/dttz.c
  sqlite/src/expr.c
  tests/ddl_no_csc2.test/t00_create_table.expected
  tests/ddl_no_csc2.test/t01_alter_table.expected
  tests/ddl_no_csc2.test/t02_create_index.expected
  tests/remsql.test/Makefile
  tests/remsql.test/README
  tests/remsql.test/lrl.options
  tests/remsql.test/output.expected
  tests/remsql.test/runit
  tests/remsql.test/t.csc2
Labels: R7, SQLite, bug, ready to review

#1577 fix count(*) per sqlite Check-in [05897ca4]
  sqlite/src/select.c
  tests/curmoves.test/t9_13.req
  tests/curmoves.test/t9_13.req.exp
Labels: SQLite

#1480 Provide tunable to abort on dta lookup lost the race error
  db/db_tunables.c
  db/db_tunables.h
  sqlite/src/vdbeaux.c
Labels: SQLite

#1600 berkdb: Fix a memory leak in the rep processor
  berkdb/rep/rep_record.c
Labels: bug
