Repository bloomberg/comdb2, pull requests merged in 2019-04, with the labels that each got.

#1487 Fix SQLite API usage for ezsystables
  sqlite/ext/comdb2/ezsystables.c
Labels: SQLite

#1486 Fix parallel sql leak
  db/dohast.c
  db/dohsql.c
  sqlite/src/expr.c
Labels: SQLite

#1438 cdb2api: Configuring DNS suffix at compile time.
  CMakeLists.txt
  cdb2api/cdb2api.c
Labels: enhancement

#1491 Fix memory leaks in the thdpool callbacks.
  bdb/rep.c
  berkdb/btree/bt_pf.c
  db/osqlcomm.c
Labels: bug

#1500 schemachange: Fix the schema change resumption check for comdb2sc
  schemachange/schemachange.c
Labels: bug

#1494 Various small bugfixes and minor enhancements pulled from PRs in progress
  bdb/tran.c
  db/sqlglue.c
  db/sqlinterfaces.c
  lua/sp.c
  sqlite/src/comdb2build.c
  tests/runtestcase
  tests/setup
Labels: R7, SQLite, bug, ready to review, testsuite

#1495 Update included SQLite to the 3.28 release (pending)...
  db/sqlglue.c
  sqlite/CMakeLists.txt
  sqlite/src/alter.c
  sqlite/src/attach.c
  sqlite/src/btree.c
  sqlite/src/btree.h
  sqlite/src/btreeInt.h
  sqlite/src/build.c
  sqlite/src/expr.c
  sqlite/src/func.c
  sqlite/src/insert.c
  sqlite/src/loadext.c
  sqlite/src/main.c
  sqlite/src/malloc.c
  sqlite/src/pager.c
  sqlite/src/parse.y
  sqlite/src/printf.c
  sqlite/src/resolve.c
  sqlite/src/select.c
  sqlite/src/shell.c
  sqlite/src/shell.c.in
  sqlite/src/sqlite.h.in
  sqlite/src/sqlite3.h
  sqlite/src/sqlite3ext.h
  sqlite/src/sqliteInt.h
  sqlite/src/sqlite_btree.h
  sqlite/src/tclsqlite.c
  sqlite/src/test1.c
  sqlite/src/test_fs.c
  sqlite/src/test_func.c
  sqlite/src/test_tclsh.c
  sqlite/src/test_vfs.c
  sqlite/src/tokenize.c
  sqlite/src/treeview.c
  sqlite/src/util.c
  sqlite/src/vacuum.c
  sqlite/src/vdbe.c
  sqlite/src/vdbeInt.h
  sqlite/src/vdbeapi.c
  sqlite/src/vdbeaux.c
  sqlite/src/vdbemem.c
  sqlite/src/wal.c
  sqlite/src/where.c
  sqlite/src/wherecode.c
  sqlite/src/whereexpr.c
  sqlite/src/window.c
  sqlite/tool/addopcodes.tcl
  sqlite/tool/mkkeywordhash.c
  tests/auth.test/t09.expected
  tests/comdb2sys.test/comdb2sys.expected
  tests/limitsortingtbl.test/sel1.expected
Labels: R7, SQLite

#1501 Authorizer callback for use with SQLite, based on PR #1305
  db/comdb2.c
  db/db_tunables.c
  db/db_tunables.h
  db/sql.h
  db/sqlinterfaces.c
  docs/pages/programming/luasp.md
  lua/sp.c
  lua/sp_int.h
  sqlite/definitions.cmake
  sqlite/src/comdb2build.c
  sqlite/src/comdb2lua.c
  sqlite/src/parse.y
  sqlite/src/sqlite.h.in
  sqlite/src/sqlite3.h
  sqlite/src/sqliteInt.h
  tests/sp.test/lrl.options
  tests/sp.test/sp.sh
  tests/sp.test/t01.req.out
  tests/tunables.test/t00_all_tunables.expected
Labels: R7, SQLite, ready to review

#1504 Reduce contention on the private blkseq.
  bdb/attr.h
  bdb/bdb_blkseq.c
  bdb/bdb_int.h
  docs/pages/config/config_files.md
  tests/tunables.test/t00_all_tunables.expected
Labels: bug, fine-tuning

#1508 reqlog: less spew from excess client stats.
  db/reqlog.c
Labels: cleanup

#1516 Reopen a temp cursor if it is closed
  bdb/temptable.c
Labels: bug

#1512 Fix pglogs_asof_thread race with clean exit.
  bbinc/thrman.h
  bdb/cursor.c
  db/process_message.c
  db/thrman.c
Labels: bug

#1515 Create osql hash before starting net
  db/sqloffload.c
Labels: bug

#1513 osql: Fix osql_blkseq_unregister race with osql_open()
  db/osqlblkseq.c
Labels: bug

#1519 Have the SIGTERM handler call clean_exit_thd
  db/comdb2.c
  db/process_message.c
Labels: bug

#1517 Authorizer callback for use with SQLite, based on PR #1305 (v2)
  db/comdb2.c
  db/db_tunables.c
  db/db_tunables.h
  db/sql.h
  db/sqlinterfaces.c
  docs/pages/programming/luasp.md
  lua/sp.c
  lua/sp_int.h
  sqlite/definitions.cmake
  sqlite/src/comdb2build.c
  sqlite/src/comdb2lua.c
  sqlite/src/parse.y
  sqlite/src/sqlite.h.in
  sqlite/src/sqlite3.h
  sqlite/src/sqliteInt.h
  tests/sp.test/lrl.options
  tests/sp.test/sp.sh
  tests/sp.test/t01.req.out
  tests/tunables.test/t00_all_tunables.expected
  util/thdpool.c
Labels: R7, SQLite, bug, ready to review

#1518 Port r6 pr1026 timepart retention1
  db/sqlinterfaces.c
  db/views.c
  sqlite/src/build.c
  sqlite/src/comdb2build.c
  tests/timepart_retention1.test/Makefile
  tests/timepart_retention1.test/README
  tests/timepart_retention1.test/lrl.options
  tests/timepart_retention1.test/run.log.alpha
  tests/timepart_retention1.test/runit
  tests/timepart_retention1.test/t.csc2
Labels: R7, SQLite

#1478 Fix some issues caught by clang
  CMakeLists.txt
  bdb/bdb_schemachange.h
  bdb/fstdump.c
  bdb/info.c
  bdb/locktest.c
  bdb/phys_rep_lsn.c
  bdb/rowlocks.c
  csc2/macc.h
  csc2/maccwrite2.c
  db/constraints.c
  db/db_metrics.c
  db/db_tunables.c
  db/db_tunables.h
  db/dohsql.c
  db/indices.h
  db/machclass.c
  db/sqlanalyze.c
  db/sqloffload.c
  db/tag.c
  db/types.c
  plugins/newsql/newsql.c
  plugins/remsql/CMakeLists.txt
  plugins/remsql/fdb_comm.c
  schemachange/sc_struct.c
  sqlite/src/vdbe.h
  sqlite/src/vdbeInt.h
  tests/tools/cdb2_close_early.c
  tests/tools/crle.c
  tools/cdb2_sqlreplay/cdb2_sqlreplay.cpp
  tools/cdb2sql/cdb2sql.cpp
  tools/pmux/pmux.cpp
Labels: SQLite

#1534 Miscellaneous changes to cdb2jdbc
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/Comdb2DatabaseMetaData.java
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/Comdb2Handle.java
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/Comdb2PreparedStatement.java
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/Comdb2Statement.java
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/DatabaseDiscovery.java
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/UnpooledDataSource.java
  cdb2jdbc/src/test/java/com/bloomberg/comdb2/jdbc/DatabaseDiscoveryTest.java
  cdb2jdbc/src/test/java/com/bloomberg/comdb2/jdbc/DatabaseMetaDataTest.java
Labels: JDBC, cleanup

#1536 A few more static analyzer errors
  db/sltdbt.c
  db/sqlexplain.c
  db/toblock.c
  sqlite/tool/lemon.c
Labels: SQLite

#1507 Fix mismatching remsql db clases
  db/fdb_fend.c
  sqlite/src/build.c
  tests/mismatch_class_remsql.test/Makefile
  tests/mismatch_class_remsql.test/README
  tests/mismatch_class_remsql.test/inserts.req.src
  tests/mismatch_class_remsql.test/lrl.options
  tests/mismatch_class_remsql.test/output.log.exp.src
  tests/mismatch_class_remsql.test/remsql.sh
  tests/mismatch_class_remsql.test/runit
  tests/mismatch_class_remsql.test/t.csc2
Labels: SQLite

#1539 Safely remove an element from a SQLite hashtable while looping over it.
  db/sqlglue.c
Labels: bug

#1531 Clean exit only when the bdb env is ready
  db/process_message.c
Labels: bug
