Repository bloomberg/comdb2, pull requests merged in 2020-04, with the labels that each got.

#2178 to not use sqlitex if remsql backend
  db/sqlinterfaces.c
Labels: PORT TO 7.0

#2193 Fix for live vutf8 schema change
  bbinc/debug_switches.h
  db/db_tunables.h
  db/types.c
  schemachange/sc_records.c
  schemachange/schemachange.c
  tests/sc_vutf8_validate.test/Makefile
  tests/sc_vutf8_validate.test/off_osql_odh_blob.testopts
  tests/sc_vutf8_validate.test/runit
  tests/tunables.test/t00_all_tunables.expected
  util/debug_switches.c
Labels: PORT TO 7.0, bug, ready to review

#2196 Fix for live vutf8 schema change (7.0)
  bbinc/debug_switches.h
  db/db_tunables.h
  db/types.c
  schemachange/sc_records.c
  schemachange/schemachange.c
  tests/sc_vutf8_validate.test/Makefile
  tests/sc_vutf8_validate.test/off_osql_odh_blob.testopts
  tests/sc_vutf8_validate.test/runit
  tests/tunables.test/t00_all_tunables.expected
  util/debug_switches.c
Labels: R7, bug
