Repository bloomberg/comdb2, pull requests merged in 2020-11, with the labels that each got.

#2566 Consistent thread pool handling of free lists by work threads.
  util/thdpool.c
Labels: R7, enhancement, ready to review

#2559 Fix analyze crash on database exit
  bbinc/debug_switches.h
  db/sqlanalyze.c
  db/sqlinterfaces.c
  tests/analyze_exit.test/Makefile
  tests/analyze_exit.test/lrl.options
  tests/analyze_exit.test/output.expected
  tests/analyze_exit.test/runit
  tests/tunables.test/t00_all_tunables.expected
  util/debug_switches.c
Labels: PORT TO 7.0, bug

#2565 Copy blobs only once
  bdb/bdb_fetch.h
  bdb/bdb_int.h
  bdb/bdb_verify.c
  bdb/fetch.c
  bdb/odh.c
  berkdb/db/db_cam.c
  db/sqlglue.c
  sqlite/src/vdbe.c
Labels: PORT TO 7.0, enhancement

#2567 Fix an eventlog crash caused by lengthy queries
  db/eventlog.c
  db/osqlsqlthr.c
Labels: PORT TO 7.0, bug

#2571 Fix double-free in query plan caching
  db/sqlinterfaces.c
Labels: PORT TO 7.0, bug

#1860 Fix cascading updates in self-referencing FK constraints
  db/block_internal.h
  db/comdb2.h
  db/constraints.c
  db/handle_buf.c
  db/record.c
  tests/constraints.test/t12.req
  tests/constraints.test/t12.req.exp
  tests/constraints.test/t13.req
  tests/constraints.test/t13.req.exp
  tests/ddl_no_csc2.test/t06_fk.expected
  tests/ddl_no_csc2.test/t06_fk.sql
  tests/sc_constraints.test/Makefile
Labels: PORT TO 7.0

#2573 BPLOG over socket
  db/CMakeLists.txt
  db/block_internal.h
  db/comdb2.c
  db/comdb2.h
  db/constraints.c
  db/db_tunables.c
  db/db_tunables.h
  db/glue.c
  db/handle_buf.c
  db/indices.c
  db/osqlblockproc.c
  db/osqlcheckboard.c
  db/osqlcheckboard.h
  db/osqlcomm.c
  db/osqlcomm.h
  db/osqlsession.c
  db/osqlsession.h
  db/osqlshadtbl.c
  db/osqlsqlnet.c
  db/osqlsqlnet.h
  db/osqlsqlsocket.c
  db/osqlsqlsocket.h
  db/osqlsqlthr.c
  db/osqlsqlthr.h
  db/process_message.c
  db/record.c
  db/sltdbt.c
  db/sql.h
  db/sqlglue.c
  db/sqlinterfaces.c
  db/sqloffload.c
  db/toblock.c
  docs/pages/config/config_files.md
  plugins/CMakeLists.txt
  plugins/newsql/newsql.c
  plugins/sockbplog/CMakeLists.txt
  plugins/sockbplog/plugin.h.in
  plugins/sockbplog/sockbplog.c
  sockpool/sockpool.c
  sqlite/ext/comdb2/activeosqls.c
  tests/curmoves.test/sockbplog.testopts
  tests/tunables.test/t00_all_tunables.expected
Labels: feature, ready to review

#2580 Fix crash when per-thread malloc is off
  bdb/odh.c
Labels: PORT TO 7.0

#2581 sp: Reset logger before executing a query
  lua/sp.c
Labels: PORT TO 7.0, enhancement

#2568 Add tunable which prevents mixed ddl and dml write schedules
  bdb/bdb_api.h
  bdb/llmeta.c
  bdb/locks.c
  db/db_tunables.c
  db/db_tunables.h
  db/osqlblockproc.c
  db/osqlcomm.c
  db/osqlsqlthr.c
  db/toblock.c
  tests/sc_lock_inversion.test/Makefile
  tests/sc_lock_inversion.test/README.txt
  tests/sc_lock_inversion.test/comdb2_oplog.csc2
  tests/sc_lock_inversion.test/lrl.options
  tests/sc_lock_inversion.test/runit
  tests/sc_lock_inversion.test/t1.csc2
  tests/sc_transactional.test/lrl.options
  tests/verify_error.test/lrl.options
Labels: WIP

#2591 Use protobuf allocator for newsql unpacking
  plugins/newsql/newsql_sbuf.c
  tests/mem_protobuf.test/Makefile
  tests/mem_protobuf.test/runit
Labels: enhancement

#2594 Fix the check that forbids use of u_longlong types
  db/tag.c
  tests/ddl_csc2.test/t00_create_table.expected
  tests/ddl_csc2.test/t00_create_table.sql
  tests/sc_datacopy.test/lrl.options
Labels: PORT TO 7.0
