Repository bloomberg/comdb2, pull requests merged in 2020-08, with the labels that each got.

#2382 Allocator index is 1-based
  mem/mem.c
Labels: PORT TO 7.0, bug

#2012 Prevent access to freed memory after trans_commit / trans_abort
  bdb/bdb_api.h
  bdb/tran.c
  db/fdb_bend_sql.c
  db/localrep.c
  db/osqlblockproc.c
  db/sqlanalyze.c
  db/sqlglue.c
  db/sqlinterfaces.c
  db/toblock.c
  schemachange/sc_alter_table.c
  schemachange/sc_queues.c
  schemachange/sc_records.c
Labels: R7, WIP

#2388 Keep track of the number of thread-pool threads that are actively performing work items.
  util/thdpool.c
Labels: PORT TO 7.0, enhancement, ready to review

#2399 Use sqlite3_free in free_functions
  sqlite/ext/comdb2/functions.c
Labels: SQLite, ready to review

#2386 Fix timer trap deadlock
  db/comdb2.c
  tests/sync_log_delete_off_reenable.test/Makefile
  tests/sync_log_delete_off_reenable.test/runit
Labels: PORT TO 7.0, bug

#2385 cdb2jdbc: turn on verify-retry and return per-statement effects
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/Comdb2Connection.java
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/Comdb2Handle.java
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/Comdb2Statement.java
  cdb2jdbc/src/test/java/com/bloomberg/comdb2/jdbc/StatementQueryEffectsTest.java
  tests/jepsen_a6.test/runit
  tests/jepsen_a6_nemesis.test/runit
  tests/jepsen_atomic_writes.test/runit
  tests/jepsen_bank.test/runit
  tests/jepsen_bank_nemesis.test/runit
  tests/jepsen_dirty_reads.test/runit
  tests/jepsen_g2.test/runit
  tests/jepsen_register.test/runit
  tests/jepsen_register_nemesis.test/runit
  tests/jepsen_sets.test/runit
Labels: JDBC

#2410 Fix datacopy race in create_sqlmaster_record
  db/comdb2.c
  db/comdb2.h
  db/sqlglue.c
  schemachange/sc_add_table.c
  schemachange/sc_alter_table.c
  schemachange/sc_callbacks.c
Labels: ready to review

#2422 usleep
  sqlite/src/func.c
  tests/auth.test/t09.expected
  tests/tools/smartbeats.c
Labels: feature

#2423 Configure row-buffering
  db/sql.h
  db/sqlinterfaces.c
  docs/pages/programming/sql.md
  plugins/newsql/newsql.c
Labels: feature

#2428 sp: Enable h/b incase push-args take time [DRQS 161737935]
  lua/sp.c
Labels: PORT TO master

#2427 Fix length of string created for sql function guid_str
  sqlite/src/func.c
  tests/guid.test/runit
Labels: SQLite

#2440 Fix null/empty parameter binding (7.0)
  cdb2api/cdb2api.c
  db/types.c
  plugins/newsql/newsql.c
  tests/tools/cdb2bind.c
Labels: R7, bug
