Repository bloomberg/comdb2, pull requests merged in 2020-10, with the labels that each got.

#2519 Remove spurious lock
  lua/sp.c
Labels: R7, bug

#2520 Tweak sql_tick
  db/sqlglue.c
Labels: PORT TO 7.0, bug

#2421 Add sqlite_sorterpenalty as tunable
  db/db_tunables.c
  db/db_tunables.h
  sqlite/src/where.c
  tests/tunables.test/t00_all_tunables.expected
Labels: SQLite

#2524 Add a test for X.509 SAN validation
  tests/ssl_san.test/Makefile
  tests/ssl_san.test/lrl.options
  tests/ssl_san.test/runit
  tests/tools/keygen.sh
Labels: testsuite

#2538 Allocate temptable resources based on the temptable type
  bdb/temptable.c
Labels: PORT TO 7.0, enhancement

#2545 Allow ECDHE ciphers
  tests/simple_ssl.test/lrl.options
  util/ssl_support.c
Labels: PORT TO 7.0, bug

#2539 Tweak bdb_create_dba_user()
  bdb/bdb_access.c
Labels: PORT TO 7.0, cleanup

#2551 Make partition-by work
  bdb/temptable.c
  tests/window.test/t00.expected
  tests/window.test/t00.sql
Labels: PORT TO 7.0, bug

#2544 Prevent unintentional duplicate writes within a stored procedure
  lua/sp.c
  tests/dupewrite.test/Makefile
  tests/dupewrite.test/README
  tests/dupewrite.test/dupe.sh
  tests/dupewrite.test/runit
  tests/dupewrite.test/t01.req
  tests/dupewrite.test/t01.req.out
  tests/dupewrite.test/t02.req
  tests/dupewrite.test/t02.req.args
  tests/dupewrite.test/t02.req.out
  tests/dupewrite.test/t02.req.tool
  tests/dupewrite.test/t03.req
  tests/dupewrite.test/t03.req.out
  tests/dupewrite.test/test.sh
  tests/fingerprints.test/t05.req
  tests/fingerprints.test/t05.req.out
Labels: R7, enhancement, ready to review

#2556 Enable better roundtripping of CSC2 and SQL data type names.
  db/sqlglue.c
  db/sqlinterfaces.c
  sqlite/src/comdb2build.c
  tests/cdb2_coltype.test/Makefile
  tests/cdb2_coltype.test/runit
  tests/cdb2_coltype.test/t01.expected
  tests/cdb2_coltype.test/t01.sql
  tests/comdb2sys.test/comdb2sys.expected
  tests/ddl_csc2.test/t01_create_table.expected
  tests/ddl_csc2.test/t01_create_table.sql
  tests/ddl_no_csc2.test/t00_create_table.expected
  tools/cdb2sql/cdb2sql.cpp
Labels: R7, enhancement, ready to review
