Repository bloomberg/comdb2, pull requests merged in 2020-07, with the labels that each got.

#2314 Log column names on mismatch
  db/db_fingerprint.c
  sqlite/src/sqlite.h.in
  sqlite/src/sqlite3.h
  sqlite/src/vdbeapi.c
Labels: PORT TO 7.0

#2323 Fix a memory leak in datetime and interval arithmetic (7.0)
  sqlite/src/vdbe.c
  tests/sql_datetime_interval_arithmetic_leak.test/Makefile
  tests/sql_datetime_interval_arithmetic_leak.test/lrl.options
  tests/sql_datetime_interval_arithmetic_leak.test/runit
Labels: R7, SQLite, bug

#2324 Fix a memory leak in datetime and interval arithmetic
  sqlite/src/vdbe.c
  tests/sql_datetime_interval_arithmetic_leak.test/Makefile
  tests/sql_datetime_interval_arithmetic_leak.test/lrl.options
  tests/sql_datetime_interval_arithmetic_leak.test/runit
Labels: PORT TO 7.0, SQLite, bug

#2190 Fix for cdb2jdbc database metadata
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/Comdb2DatabaseMetaData.java
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/Comdb2Statement.java
  cdb2jdbc/src/test/java/com/bloomberg/comdb2/jdbc/DatabaseMetaDataTest.java
Labels: JDBC, ready to review

#2227 comdb2ar: handle certificates in the data directory
  tools/comdb2ar/serialise.cpp
Labels: PORT TO 7.0, bug, ready to review

#2325 Disable Nagle's Algorithm for remote SQL connections
  db/sqlglue.c
Labels: PORT TO 7.0, enhancement, ready to review

#2334 Fix for Smartbeats
  lua/sp.c
  lua/sp.h
  plugins/newsql/newsql.c
Labels: PORT TO 7.0, bug

#2340 Tick more frequently in luabb_trigger_register()
  lua/sp.c
Labels: PORT TO 7.0, bug

#2343 Introduce curtran_gettran, and utilize for a few db-layer functions
  bdb/bdb_int.h
  bdb/llmeta.c
  db/db_metrics.c
  db/fdb_fend.c
  db/glue.c
  db/sql.h
  db/sqlglue.c
  db/sqlinterfaces.c
  db/sqloffload.c
  sqlite/ext/comdb2/triggers.c
  sqlite/src/comdb2build.c
Labels: ready to review

#2351 Modify systables to use curtran_gettran
  db/dbqueuedb.c
  db/sqlglue.c
  sqlite/ext/comdb2/indexuse.c
  sqlite/ext/comdb2/procedures.c
  sqlite/ext/comdb2/schistory.c
  sqlite/ext/comdb2/scstatus.c
  sqlite/ext/comdb2/tablepermissions.c
  sqlite/ext/comdb2/tablesizes.c
  sqlite/ext/comdb2/users.c
  sqlite/ext/comdb2/views.c
  tests/sc_rebuilds.test/extralock.testopts
  tests/schemalk.test/extralock.testopts
  tests/systable_locking.test/runit
Labels: ready to review

#2335 Fix temp cursor leak
  bdb/temptable.c
  tests/temp_table_cursor_leak.test/Makefile
  tests/temp_table_cursor_leak.test/lrl.options
  tests/temp_table_cursor_leak.test/runit
Labels: PORT TO 7.0, bug, ready to review

#1884 Fix fingerprinting and its associated accounting for SQL queries executed inside Lua stored procedures (backport of #1682, #1703, #1708, #1965, et al).
  db/db_fingerprint.c
  db/fdb_bend_sql.c
  db/sql.h
  db/sqlglue.c
  db/sqlinterfaces.c
  docs/src/sqlitegen/bubble-generator-data.tcl
  lua/sp.c
  sqlite/ext/comdb2/fingerprints.c
  sqlite/src/parse.y
  sqlite/src/tokenize.c
  sqlite/src/vdbeInt.h
  sqlite/src/vdbeaux.c
  sqlite/tool/mkkeywordhash.c
  tests/auth.test/t09.expected
  tests/comdb2sys.test/comdb2sys.expected
  tests/fingerprints.test/Makefile
  tests/fingerprints.test/README
  tests/fingerprints.test/fp.sh
  tests/fingerprints.test/lrl.options
  tests/fingerprints.test/runit
  tests/fingerprints.test/t01.req
  tests/fingerprints.test/t01.req.out
  tests/fingerprints.test/t02.req
  tests/fingerprints.test/t02.req.args
  tests/fingerprints.test/t02.req.out
  tests/fingerprints.test/t02.req.tool
  tests/fingerprints.test/t03.req
  tests/fingerprints.test/t03.req.out
  tests/fingerprints.test/t04.req
  tests/fingerprints.test/t04.req.out
  tests/fingerprints.test/test.sh
Labels: R7, enhancement, port, ready to review

#2364 Disable INDEXED BY and NOT INDEXED syntax for backward compatibility.
  sqlite/src/parse.y
  tests/yast.test/comdb2.test
Labels: PORT TO 7.0, R7, enhancement, ready to review

#2365 Disable INDEXED BY and NOT INDEXED syntax for backward compatibility. (backport)
  sqlite/src/parse.y
  tests/yast.test/comdb2.test
Labels: R7, SQLite, enhancement, ready to review

#2374 Address deadlocks for tests running in standalone mode
  bdb/bdb_int.h
  bdb/lite.c
  berkdb/lock/lock.c
  db/db_tunables.c
  db/db_tunables.h
  db/sqlglue.c
Labels: ready to review

#2367 cdb2api bug fixes: pmux, garbage config and the local tier
  cdb2api/cdb2api.c
  tests/dc.test/Makefile
  tests/dc.test/runit
  tests/tools/cdb2api_unit.c
Labels: bug

#2368 Provide 'nextsequence' as a default dbstore type
  bdb/bdb_api.h
  bdb/lite.c
  bdb/llmeta.c
  csc2/csctypes.h
  csc2/macc_so.c
  csc2/macclex.l
  csc2/maccparse.y
  db/comdb2.h
  db/db_tunables.c
  db/db_tunables.h
  db/record.c
  db/sqlglue.c
  db/sqlinterfaces.c
  db/tag.c
  db/tag.h
  db/types.c
  db/types.h
  docs/images/alter-table-ddl.gif
  docs/images/column-constraint.gif
  docs/images/schema-section.gif
  docs/pages/programming/sql.md
  docs/pages/programming/system_tables.md
  docs/pages/programming/table_schema.md
  docs/src/sqlitegen/bubble-generator-data.tcl
  schemachange/sc_add_table.c
  schemachange/sc_alter_table.c
  schemachange/sc_drop_table.c
  schemachange/sc_rename_table.c
  sqlite/ext/comdb2/columns.c
  sqlite/src/comdb2build.c
  sqlite/src/comdb2build.h
  sqlite/src/dttz.c
  sqlite/src/func.c
  sqlite/src/parse.y
  sqlite/src/sqlite.h.in
  sqlite/src/sqlite3.h
  sqlite/src/vdbeInt.h
  sqlite/src/vdbeapi.c
  sqlite/src/vdbeaux.c
  sqlite/src/vdbemem.c
  sqlite/tool/mkkeywordhash.c
  tests/auth.test/t09.expected
  tests/comdb2sys.test/comdb2sys.expected
  tests/ddl_no_csc2.test/t00_create_table.expected
  tests/ddl_no_csc2.test/t01_alter_table.expected
  tests/ddl_no_csc2.test/t02_create_index.expected
  tests/nextsequence.test/Makefile
  tests/nextsequence.test/lrl.options
  tests/nextsequence.test/runit
  tests/nextsequence.test/seq.csc2
  tests/nextsequence.test/seqcstring.csc2
  tests/nextsequence.test/seqdatetime.csc2
  tests/nextsequence.test/seqdouble.csc2
  tests/nextsequence.test/seqlonglong.csc2
  tests/nextsequence.test/seqnonextsequence.csc2
  tests/nextsequence.test/seqnonull.csc2
  tests/nextsequence.test/seqnoseq.csc2
  tests/nextsequence.test/seqshort.csc2
  tests/tunables.test/t00_all_tunables.expected
Labels: ready to review

#2378 Minor cleanups to SQLite integration related to the new 'NEXTSEQUENCE' feature.
  db/sqlinterfaces.c
  sqlite/src/vdbeInt.h
  sqlite/src/vdbeapi.c
  sqlite/tool/mkkeywordhash.c
Labels: R7, SQLite, cleanup, ready to review

#2270 Reporting size of temporary files
  bdb/bdb_api.h
  bdb/file.c
  db/process_message.c
  docs/pages/programming/system_tables.md
  sqlite/CMakeLists.txt
  sqlite/ext/comdb2/comdb2systblInt.h
  sqlite/ext/comdb2/tables.c
  sqlite/ext/comdb2/temporary_file_sizes.c
  tests/auth.test/t09.expected
  tests/cdb2sql.test/t00.expected
  tests/comdb2sys.test/comdb2sys.expected
  tests/comdb2sys.test/comdb2sys.req
  tests/userschema.test/t00.expected
  tests/userschema.test/t07.expected
  tests/userschema.test/t09.expected
Labels: enhancement, ready to review
