Repository bloomberg/comdb2, pull requests merged in 2020-06, with the labels that each got.

#2276 Fix DOHAST memory leak (7.0)
  db/dohast.c
  tests/dohsql_leaks.test/Makefile
  tests/dohsql_leaks.test/runit
Labels: R7, bug, ready to review

#2281 Fix bdb_temp_table_truncate memory leak (7.0)
  bdb/temptable.c
  tests/temp_table_truncate_leak.test/Makefile
  tests/temp_table_truncate_leak.test/lrl.options
  tests/temp_table_truncate_leak.test/runit
Labels: R7, bug

#2277 Fix DOHAST memory leak
  db/dohast.c
  tests/dohsql_leaks.test/Makefile
  tests/dohsql_leaks.test/runit
Labels: bug, ready to review

#2280 Fix bdb_temp_table_truncate memory leak
  bdb/temptable.c
  tests/temp_table_truncate_leak.test/Makefile
  tests/temp_table_truncate_leak.test/lrl.options
  tests/temp_table_truncate_leak.test/runit
Labels: bug

#2273 Replication lag
  bdb/bdb_api.h
  bdb/info.c
  sqlite/ext/comdb2/repl_stats.c
  tests/repl_stats.test/Makefile
  tests/repl_stats.test/runit
Labels: enhancement, ready to review

#2285 Serialize a protobuf object to sbuf directly (7.0)
  plugins/newsql/newsql.c
  tests/protobuf_to_sbuf.test/Makefile
  tests/protobuf_to_sbuf.test/lrl.options
  tests/protobuf_to_sbuf.test/runit
  tests/row_buf_max_sz.test/lrl.options
  tests/row_buf_max_sz.test/runit
Labels: R7, enhancement

#2184 Serialize a protobuf object to sbuf directly
  plugins/newsql/newsql.c
  tests/protobuf_to_sbuf.test/Makefile
  tests/protobuf_to_sbuf.test/lrl.options
  tests/protobuf_to_sbuf.test/runit
  tests/row_buf_max_sz.test/lrl.options
  tests/row_buf_max_sz.test/runit
Labels: enhancement, ready to review

#2291 Supporting multiple constraints sections in csc2 (7.0)
  csc2/macc_so.c
  csc2/maccparse.y
  tests/constraints.test/t14.req
  tests/constraints.test/t14.req.exp
Labels: R7, bug

#2292 Test multiple constraints sections in csc2
  tests/constraints.test/t14.req
  tests/constraints.test/t14.req.exp
Labels: testsuite

#2171 Experimental changes to detect 'stuck' clients...
  db/db_tunables.c
  db/db_tunables.h
  db/sql.h
  db/sqlinterfaces.c
  db/watchdog.c
  sqlite/ext/comdb2/connections.c
Labels: R7, enhancement

#2293 Fix double counting of num_accepts (7.0)
  net/net.c
Labels: R7, bug

#2294 Fix double counting of num_accepts
  net/net.c
Labels: bug

#2054 Add fingerprint column to active connections virtual table
  db/db_fingerprint.c
  db/sql.h
  db/sqlinterfaces.c
  sqlite/ext/comdb2/connections.c
Labels: PORT TO 7.0, PORT TO R6, R7, SQLite, WIP, enhancement

#2086 Experimental changes to fix stat4dump heap management
  bbinc/thread_malloc.h
  db/comdb2.c
  db/sql.h
  db/sqlglue.c
  db/sqlinterfaces.c
  util/thread_malloc.c
Labels: ready to review

#2058 Add fingerprint column to active connections virtual table (backport)
  db/db_fingerprint.c
  db/sql.h
  db/sqlinterfaces.c
  sqlite/ext/comdb2/connections.c
Labels: R7, SQLite, WIP, enhancement

#2019 Add comdb2_test_log() SQL function and its associated debugging tunable
  db/db_tunables.c
  db/db_tunables.h
  sqlite/src/func.c
Labels: R7, enhancement

#1822 Add 'class' to the comdb2_sysinfo() SQL function
  sqlite/src/func.c
Labels: PORT TO R6, R7, SQLite, ready to review

#2088 Cherrypick of SQLite query optimizer enhancement for STAT4
  sqlite/src/where.c
  sqlite/src/whereInt.h
  tests/yast.test/analyzeG.test
  tests/yast.test/delete1.test
  tests/yast.test/lrl.options
  tests/yast.test/tester.tcl
Labels: R7, SQLite, enhancement

#2299 cdb2api: Fix incorrect rollback behavior
  cdb2api/cdb2api.c
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/Comdb2Handle.java
  tests/cdb2api_rollback_rc.test/Makefile
  tests/cdb2api_rollback_rc.test/expected
  tests/cdb2api_rollback_rc.test/runit
Labels: bug

#1980 Fix some memory/resource leaks in the schema change subsystem
  schemachange/sc_logic.c
  schemachange/sc_struct.c
  schemachange/schemachange.c
Labels: PORT TO 7.0, R7, bug, ready to review

#1982 Fix some memory/resource leaks in the schema change subsystem (7.0 port)
  schemachange/sc_logic.c
  schemachange/sc_struct.c
  schemachange/schemachange.c
Labels: R7, bug, ready to review

#1967 Add rc checking to tid->commit in bdb_close_int
  bdb/file.c
Labels: R7, WIP, cleanup
