Repository bloomberg/comdb2, pull requests merged in 2020-12, with the labels that each got.

#2579 Completely remove all support for numerically prioritizing SQL queries.
  bbinc/comdb2_ruleset.h
  bbinc/priority_queue.h
  bbinc/thdpool.h
  bdb/bdb_verify.c
  bdb/rep.c
  berkdb/btree/bt_pf.c
  berkdb/build/db.h
  berkdb/mp/mp_sync.c
  berkdb/rep/rep_record.c
  db/appsock_handler.c
  db/comdb2_ruleset.c
  db/db_tunables.h
  db/dohsql.c
  db/fdb_bend_sql.c
  db/osql_srs.c
  db/osqlpfthdpool.c
  db/sql.h
  db/sqlglue.c
  db/sqlinterfaces.c
  docs/pages/config/ruleset.md
  lua/sp.c
  plugins/newsql/newsql_sbuf.c
  sqlite/ext/comdb2/sqlpoolqueue.c
  sqlite/src/func.c
  tests/ruleset.test/README
  tests/ruleset.test/ruleset.sh
  tests/ruleset.test/t01.ruleset
  tests/ruleset.test/t02.req.out
  tests/ruleset.test/t02.req.out.alt
  tests/tools/test_threadpool.c
  tools/comdb2ar/file_info.cpp
  tools/comdb2ar/file_info.h
  tools/comdb2ar/serialise.cpp
  util/CMakeLists.txt
  util/priority_queue.c
  util/thdpool.c
Labels: SQLite, ready to review, refactor

#2608 Enable per-thread malloc for libevent net
  db/handle_buf.c
  mem/mem.h
  net/event.c
  net/net.c
  tests/netmem.test/runit
  util/thdpool.c
Labels: cleanup, enhancement

#2606 Synchronous osql cancellation
  bbinc/debug_switches.h
  db/osqlsession.c
  db/osqlsqlthr.c
  tests/sync_osql_cancel.test/Makefile
  tests/sync_osql_cancel.test/runit
  tests/tunables.test/t00_all_tunables.expected
  util/debug_switches.c
Labels: enhancement

#2607 Synchronous osql cancellation (R7)
  db/osqlsession.c
  db/osqlsqlthr.c
  tests/sync_osql_cancel.test/Makefile
  tests/sync_osql_cancel.test/lrl.options
  tests/sync_osql_cancel.test/runit
Labels: R7, enhancement

#2620 Add a knob for synchronous osql cancellation
  db/db_tunables.c
  db/db_tunables.h
  db/osqlsqlthr.c
Labels: R7

#2614 Minor summarizer changes for theoretically better disk performance
  bdb/summarize.c
Labels: cleanup

#2617 Add alternate SQL normalization algorithm with better unary operator recognition.
  db/db_tunables.c
  db/db_tunables.h
  db/sqlinterfaces.c
  sqlite/src/func.c
  sqlite/src/sqliteInt.h
  sqlite/src/tokenize.c
  sqlite/src/vdbeapi.c
  tests/auth.test/t09.expected
  tests/replay_eventlog.test/lrl.options
  tests/yast.test/normalize.test
  tests/yast.test/tester.tcl
Labels: PORT TO 7.0, R7, SQLite, enhancement, ready to review

#2609 Fix leaks from recent bplog changes
  db/comdb2.h
  db/osqlsession.c
  db/osqlsqlsocket.c
  db/sltdbt.c
  plugins/sockbplog/sockbplog.c
  tests/bplog_leaks.test/Makefile
  tests/bplog_leaks.test/runit
  tests/bplog_leaks.test/sockbplog.testopts
Labels: bug

#2585 Convert SQLite values to Comdb2 row data directly
  db/comdb2.c
  db/comdb2.h
  db/sql.h
  db/sqlglue.c
  sqlite/src/insert.c
  sqlite/src/sqliteInt.h
  sqlite/src/vdbe.c
  sqlite/src/vdbeInt.h
  tests/explain.test/run.log.exp
  tests/op_makerecord.test/Makefile
  tests/op_makerecord.test/lrl.options
  tests/op_makerecord.test/runit
  tests/tools/CMakeLists.txt
  tests/tools/makerecord_timer.c
  tests/tunables.test/t00_all_tunables.expected
Labels: SQLite, enhancement

#2626 Fix misreporting of request queue related metrics
  bbinc/thdpool.h
  db/db_metrics.c
  db/handle_buf.c
  db/sqlinterfaces.c
  tests/queue_depth.test/Makefile
  tests/queue_depth.test/lrl.options
  tests/queue_depth.test/runit
  util/thdpool.c
Labels: PORT TO 7.0, bug

#2625 sqlite: Fix an OP_NoConflict optimization
  db/sqlglue.c
  sqlite/src/vdbe.c
  tests/upsert.test/t00_upsert.expected
  tests/upsert.test/t00_upsert.sql
Labels: PORT TO 7.0
