Repository bloomberg/comdb2, pull requests merged in 2020-02, with the labels that each got.

#2066 sqlite: register date functions correctly
  sqlite/src/main.c
Labels: PORT TO 7.0

#1883 Fix a mutex/memory leak if sqlite3_step() fails in create_temp_table() (backport).
  db/sqlglue.c
  lua/sp.c
Labels: R7, bug, port, ready to review

#1997 sqlitex: Changes to comdb2-core to allow use of an older sqlite versi…
  bbinc/comdb2_plugin.h
  bbinc/comdb2_query_preparer.h
  bdb/bdb_api.h
  db/db_fingerprint.c
  db/db_tunables.c
  db/db_tunables.h
  db/fdb_fend.c
  db/plugin_handler.c
  db/sql.h
  db/sqlglue.c
  db/sqlinterfaces.c
  lua/sp.c
  plugins/newsql/newsql.c
  sqlite/ext/comdb2/clientstats.c
  sqlite/src/build.c
Labels: R7, SQLite

#2090 Fixes in user authentication
  bbinc/cdb2_constants.h
  docs/pages/programming/auth.md
  plugins/newsql/newsql.c
  tests/userschema.test/t09.expected
  tests/userschema.test/t09.req
Labels: PORT TO 7.0
