Repository bloomberg/comdb2, pull requests merged in 2020-03, with the labels that each got.

#2085 Delay a deadlock retry based on toblock() run time
  db/sltdbt.c
Labels: enhancement

#2100 Backport the comdb2_user() SQL function from master.
  db/sql.h
  db/sqlinterfaces.c
  sqlite/src/func.c
  tests/auth.test/t00.expected
  tests/auth.test/t00.req
  tests/auth.test/t01.expected
  tests/auth.test/t01.req
  tests/auth.test/t02.expected
  tests/auth.test/t02.req
  tests/auth.test/t03.expected
  tests/auth.test/t03.req
Labels: R7, SQLite, enhancement

#2173 Use Canonical Name everywhere
  bbinc/bb_oscompat.h
  bdb/bdb_net.c
  bdb/file.c
  db/autoanalyze.c
  db/comdb2.c
  db/comdb2.h
  db/config.c
  db/db_metrics.c
  db/db_tunables.h
  db/dbqueuedb.c
  db/debug.c
  db/eventlog.c
  db/fdb_boots.c
  db/glue.c
  db/handle_buf.c
  db/localrep.c
  db/osqlblockproc.c
  db/osqlcheckboard.c
  db/osqlcomm.c
  db/osqluprec.c
  db/phys_rep.c
  db/process_message.c
  db/pushlogs.c
  db/record.c
  db/rmtpolicy.c
  db/rowlocks_bench.c
  db/sqlanalyze.c
  db/sqlglue.c
  db/sqlinterfaces.c
  db/toblock.c
  db/trigger.h
  db/views.c
  db/watchdog.c
  net/testnet.c
  plugins/dbqueuedb/dbqueuedb.c
  plugins/newsql/newsql.c
  plugins/remsql/fdb_comm.c
  schemachange/sc_add_table.c
  schemachange/sc_alter_table.c
  schemachange/sc_csc2.c
  schemachange/sc_logic.c
  schemachange/sc_queues.c
  schemachange/sc_records.c
  schemachange/sc_stripes.c
  schemachange/sc_util.c
  schemachange/schemachange.c
  util/bb_oscompat.c
  util/rtcpu.c
Labels: bug
