Repository bloomberg/comdb2, pull requests merged in 2020-09, with the labels that each got.

#2424 Count vdbe sorter rewind toward total cost
  db/sqlglue.c
  sqlite/src/vdbeInt.h
  sqlite/src/vdbesort.c
Labels: SQLite

#2461 cdb2jdbc: Fix mishandling of driver defaults
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/Comdb2Connection.java
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/Comdb2Handle.java
  cdb2jdbc/src/test/java/com/bloomberg/comdb2/jdbc/StatementQueryEffectsTest.java
  cdb2jdbc/src/test/java/com/bloomberg/comdb2/jdbc/VerifyRetryTest.java
Labels: JDBC

#2473 Attempt to make sure that 'RECNUM' and 'UNIQNULLS' are properly roundtripped from/to CSC2.
  db/sqlglue.c
  sqlite/src/comdb2build.c
  tests/ddl_no_csc2.test/t00_create_table.expected
  tests/ddl_no_csc2.test/t01_alter_table.expected
  tests/ddl_no_csc2.test/t02_create_index.expected
Labels: R7, SQLite, enhancement, ready to review

#2475 For a single-node cluster, always attempt to enter the SQL queue. Also, fixes to terminology in comments, docs, and status output.
  bdb/attr.h
  db/process_message.c
  db/sqlinterfaces.c
  docs/pages/operating/op.md
  docs/pages/programming/system_tables.md
  util/thdpool.c
Labels: R7, enhancement, ready to review

#2393 Authorization support for time partitions
  bdb/bdb_access.c
  bdb/bdb_api.h
  bdb/llmeta.c
  db/bpfunc.c
  db/comdb2.c
  db/dohsql.c
  db/timepart_systable.h
  db/views.c
  db/views.h
  db/views_serial.c
  db/views_systable.c
  schemachange/sc_add_table.c
  schemachange/sc_add_table.h
  schemachange/sc_drop_table.c
  schemachange/sc_drop_table.h
  schemachange/sc_struct.c
  schemachange/schemachange.c
  schemachange/schemachange.h
  sqlite/CMakeLists.txt
  sqlite/ext/comdb2/comdb2systblInt.h
  sqlite/ext/comdb2/tables.c
  sqlite/ext/comdb2/timepartpermissions.c
  tests/auth.test/t09.expected
  tests/cdb2sql.test/t00.expected
  tests/comdb2sys.test/comdb2sys.expected
  tests/timepart_auth.test/Makefile
  tests/timepart_auth.test/README
  tests/timepart_auth.test/lrl.options
  tests/timepart_auth.test/runit
  tests/timepart_auth.test/t00_insert.expected
  tests/timepart_auth.test/t00_insert.sql
  tests/timepart_auth.test/t01_ddl.expected
  tests/timepart_auth.test/t01_ddl.sql
  tests/userschema.test/t00.expected
  tests/userschema.test/t07.expected
  tests/userschema.test/t09.expected
Labels: SQLite

#2478 logmsg optimization
  util/logmsg.c
Labels: PORT TO 7.0, enhancement

#2482 Store query data in cache
  db/sql.h
  db/sqlinterfaces.c
Labels: R7, bug

#2491 Fix a race condition between net accept and clean exit
  bbinc/portmuxapi.h
  db/comdb2.c
  db/db_tunables.c
  db/db_tunables.h
  util/portmuxusr.c
Labels: R7, bug

#2409 Exclude sqlite table-valued functions from comdb2_systables
  db/sqlglue.c
  docs/pages/programming/system_tables.md
  sqlite/CMakeLists.txt
  sqlite/ext/comdb2/comdb2systblInt.h
  sqlite/ext/comdb2/ezsystables.c
  sqlite/ext/comdb2/ezsystables.h
  sqlite/ext/comdb2/permissions.c
  sqlite/ext/comdb2/systables.c
  sqlite/ext/comdb2/tablepermissions.c
  sqlite/ext/comdb2/tables.c
  sqlite/ext/comdb2/timepartpermissions.c
  sqlite/ext/misc/json1.c
  sqlite/ext/misc/series.c
  sqlite/src/sqlite.h.in
  sqlite/src/sqlite3.h
  tests/auth.test/t09.expected
  tests/auth.test/t11.expected
  tests/cdb2sql.test/t00.expected
  tests/comdb2sys.test/comdb2sys.expected
  tests/timepart_auth.test/t00_insert.expected
  tests/timepart_auth.test/t01_ddl.expected
  tests/userschema.test/t00.expected
  tests/userschema.test/t00.req
  tests/userschema.test/t07.expected
  tests/userschema.test/t09.expected
Labels: SQLite

#2501 Tweak systbl_proc_leak test
  tests/systbl_proc_leak.test/lrl.options
  tests/systbl_proc_leak.test/runit
Labels: testsuite

#2490 DDL-style no-csc2 schema change commands do not work on time partitions
  sqlite/src/comdb2build.c
  tests/ddl_no_csc2.test/runit
  tests/ddl_no_csc2.test/t10_view_timepart.expected
  tests/ddl_no_csc2.test/t10_view_timepart.sql
  tests/ddl_no_csc2.test/t11_timepart.expected
  tests/ddl_no_csc2.test/t11_timepart.sql
Labels: PORT TO 7.0

#2498 Support multiple SQL engine thread pools and expose them to rulesets
  bbinc/comdb2_ruleset.h
  bbinc/thdpool.h
  bdb/bdb_net.c
  bdb/rep.c
  db/CMakeLists.txt
  db/appsock_handler.c
  db/comdb2.c
  db/comdb2.h
  db/comdb2_ruleset.c
  db/db_metrics.c
  db/db_tunables.h
  db/dohsql.c
  db/osqlpfthdpool.c
  db/process_message.c
  db/sql.h
  db/sqlinterfaces.c
  db/sqlpool.c
  db/thrman.c
  db/verify.c
  docs/pages/config/config_files.md
  docs/pages/config/ruleset.md
  lua/sp.c
  sqlite/ext/comdb2/sqlpoolqueue.c
  tests/ruleset.test/ruleset.sh
  tests/ruleset.test/t01.ruleset
  tests/ruleset.test/t02.req.out
  tests/ruleset.test/t02.req.out.alt
  tests/ruleset.test/t04.ruleset
  tests/tools/test_threadpool.c
  tests/tunables.test/t00_all_tunables.expected
  util/thdpool.c
Labels: R7, enhancement, ready to review

#2479 Smartbeats for trigger deregistration
  lua/sp.c
Labels: PORT TO 7.0, bug, ready to review

#2505 Fix remsql writes which involve multiple index lookups
  db/fdb_fend.c
  db/fdb_fend.h
  db/sqlglue.c
  tests/remsql.test/output.expected
  tests/remsql.test/runit
Labels: PORT TO 7.0, bug, ready to review

#2448 Emit more diagnostic information when the watchdog is triggered.
  bdb/bdb_api.h
  bdb/rep.c
  db/watchdog.c
Labels: enhancement

#2509 Properly reset 'sqlthdstate->query_preparer_running' to prevent asserts in the debug build.
  db/sqlpool.c
Labels: R7, cleanup, ready to review

#2510 Fix DDL backout in the block processor
  bbinc/debug_switches.h
  db/toblock.c
  tests/sc_ddl_backout.test/rowlocks.testopts
  tests/sc_ddl_backout.test/runit
  tests/tunables.test/t00_all_tunables.expected
  util/debug_switches.c
Labels: PORT TO 7.0, bug

#2513 Fix random -105 in transactions with big blobs
  plugins/newsql/newsql.c
Labels: PORT TO 7.0

#2512 Make sure the test suite has access to the 'pstack' command.
  tests/docker/Dockerfile.install
Labels: enhancement, ready to review, testsuite

#2252 Remove stop-threads
  db/comdb2.c
  db/comdb2.h
  db/db_tunables.c
  db/db_tunables.h
  db/glue.c
  db/translistener.c
  db/trigger.c
  plugins/dbqueuedb/dbqueuedb.c
  schemachange/sc_queues.c
Labels: ready to review
