Repository bloomberg/comdb2, pull requests merged in 2020-01, with the labels that each got.

#1992 Verify: stop verify when client disconnected and not verbose
  bdb/bdb_verify.c
  bdb/bdb_verify.h
  db/comdb2.h
  db/process_message.c
  db/sqlglue.c
  db/verify.c
  lua/sp.c
  lua/syssp.c
  tests/insert_lots.test/README
  tests/insert_lots.test/runit
Labels: PORT TO 7.0

#1890 Make sqlite PRNG context thread-local
  sqlite/src/random.c
Labels: PORT TO 7.0, SQLite

#1882 Fix use of uninitialized bytes as reported by valgrind (backport).
  sqlite/ext/comdb2/procedures.c
Labels: R7, bug, port, ready to review

#2034 Bring back trigger/consumer ctrace
  db/trigger.c
  lua/sp.c
Labels: PORT TO master

#2038 TLSv1.3 post-handshake authentication, ASLR, etc.
  bbinc/sbuf2.h
  bbinc/ssl_io.h
  bbinc/ssl_support.h
  cdb2api/cdb2api.c
  db/fdb_fend.c
  db/ssl_bend.c
  net/net.c
  plugins/newsql/newsql.c
  plugins/remsql/fdb_comm.c
  tests/mem_tracker.test/runit
  tests/simple_ssl.test/runit
  tests/tmptbl.test/t00.expected
  util/sbuf2.c
  util/ssl_io.c
Labels: bug
