Repository bloomberg/comdb2, pull requests merged in 2021-04, with the labels that each got.

#2759 Cherrypick of SQLite 3.28 branch performance improvement [263293f1e6db2603].
  db/db_tunables.c
  db/db_tunables.h
  sqlite/src/analyze.c
  sqlite/src/sqliteInt.h
  sqlite/src/where.c
  tests/yast.test/runit
  tests/yast.test/stat4scan.testopts
  tests/yast.test/whereG.test
Labels: R7, SQLite, enhancement, ready to review

#2797 cdb2jdbc: Add a HealthChecker callback
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/Driver.java
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/HealthChecker.java
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/SockIO.java
Labels: JDBC, enhancement

#2753 Fix Number to Datetime conversion
  db/types.c
  tests/datetime.test/t18.expected
  tests/datetime.test/t18.sql
Labels: bug, ready to review

#2805 Ensure that a cached SQL hint statement is not discarded
  db/sqlinterfaces.c
Labels: PORT TO master, R7, bug

#2800 cdb2jdbc: tweak pom.xml
  cdb2jdbc/pom.xml
Labels: JDBC, cleanup

#2810 Ensure that a cached SQL hint statement is not discarded
  db/sql_stmt_cache.c
Labels: bug, ready to review

#2813 Perform 'legacy_schema' checks only on master node
  csc2/macc_so.c
  db/glue.c
Labels: PORT TO 7.0
