Repository bloomberg/comdb2, pull requests merged in 2021-09, with the labels that each got.

#2942 Fix SQLite cost estimate
  sqlite/src/where.c
Labels: ready to review, SQLite, PORT TO master

#2946 Show byte array values in stat4dump
  db/sqlglue.c
Labels: enhancement

#2953 Do type checks for first non-typed call for each fingerprint
  db/db_fingerprint.c
  db/sql.h
Labels: PORT TO master

#2963 Add missing header
  bdb/cursor_ll.c
  bdb/rep_qstat.c
Labels: PORT TO 7.0

#2962 Fix crash when dereferencing invalid address
  sqlite/src/vdbeaux.c
  sqlite/src/vdbemem.c
  tests/sql.test/t12_01.req
  tests/sql.test/t12_01.req.exp
Labels: bug, SQLite, PORT TO 7.0

#2965 Expert mode: Ignore non-indexable fields
  db/sqlglue.c
  sqlite/ext/expert/sqlite3expert.c
  sqlite/src/expr.c
  sqlite/src/sqlite.h.in
  sqlite/src/sqlite3.h
  sqlite/src/where.c
  tests/comdb2expert.test/t03.expected
  tests/comdb2expert.test/t03.req
Labels: PORT TO master

#2972 trigger: Move subscription setup from __db_open into __bam_open
  berkdb/btree/bt_open.c
  berkdb/db/db_open.c
Labels: PORT TO master
