Repository bloomberg/comdb2, pull requests merged in 2021-05, with the labels that each got.

#2831 Reduce protobuf memory footprint
  cdb2api/cdb2api.c
  db/sql.h
  db/sqlinterfaces.c
  plugins/newsql/newsql.c
  plugins/newsql/newsql_sbuf.c
  protobuf/sqlquery.proto
  protobuf/sqlresponse.proto
Labels: enhancement

#2830 bulkimport: do not check schemalk during bdb_open_again
  bdb/bdb_api.h
  bdb/file.c
Labels: PORT TO master

#2729 Better handling of SQLite error messages
  cdb2jdbc/src/test/java/com/bloomberg/comdb2/jdbc/TimeoutTest.java
  cdb2jdbc/src/test/java/com/bloomberg/comdb2/jdbc/UnpooledDataSourceTest.java
  db/sqlglue.c
  db/sqlinterfaces.c
  sqlite/src/main.c
  sqlite/src/sqlite.h.in
  sqlite/src/sqlite3.h
  sqlite/src/vdbe.c
  tests/cdb2api.test/t29.expected
Labels: SQLite, error-handling, ready to review

#2793 FK: cascaded deletes could fail for child tables with partial indices
  db/constraints.c
  db/record.c
  tests/rawindex.test/t15.req
  tests/rawindex.test/t15.req.exp
Labels: PORT TO 7.0

#2822 Return sc errors to both SQL clients and comdb2sc
  cdb2api/cdb2api.h
  csc2/macc_so.c
  db/comdb2.h
  db/constraints.c
  db/reqdebug.c
  db/sqlinterfaces.c
  db/tag.c
  schemachange/sc_add_table.c
  schemachange/sc_alter_table.c
  schemachange/sc_csc2.c
  schemachange/sc_drop_table.c
  schemachange/sc_fastinit_table.c
  schemachange/sc_records.c
  schemachange/sc_rename_table.c
  schemachange/sc_util.c
  schemachange/sc_view.c
  tests/constraints.test/t10.req.exp
  tests/datetime.test/t14.expected
  tests/ddl_no_csc2.test/t06_fk.expected
  tests/ddl_no_csc2.test/t11_cascade_drop.expected
  tests/ddl_no_csc2.test/t12_bad_index_name.expected
  tests/ddl_no_csc2.test/t12_bad_index_name.sql
  tests/sc_add_vutf8.test/runit
Labels: error-handling
