Repository bloomberg/comdb2, pull requests merged in 2021-01, with the labels that each got.

#2629 Honor watchthreshold
  db/db_tunables.h
  db/watchdog.c
  tests/tunables.test/t00_all_tunables.expected
Labels: PORT TO 7.0

#1923 comdb2_tunables: present int/double tunable values as string
  sqlite/ext/comdb2/tunables.c
  tests/tunables.test/t00_all_tunables.expected
  tests/tunables.test/t01_dyn_tunables.expected
Labels: SQLite

#2685 Fix MakeRecord optimization
  db/sqlglue.c
  sqlite/src/vdbe.c
  tests/basic.test/nogenid48.testopts
Labels: bug
