Repository bloomberg/comdb2, pull requests merged in 2021-03, with the labels that each got.

#2739 Fix crash caused by uninitialized Mem.tz
  sqlite/src/vdbeaux.c
  tests/datetime.test/t16.expected
  tests/datetime.test/t16.sql
Labels: PORT TO 7.0, SQLite, bug

#2746 comdb2_tunables: Fix a crash during self-join
  sqlite/ext/comdb2/tunables.c
  tests/tunables.test/t00_all_tunables.expected
  tests/tunables.test/t01_dyn_tunables.expected
  tests/tunables.test/t01_dyn_tunables.sql
Labels: PORT TO master

#2728 Exclude sqlite_stats from querylimit
  db/sqlglue.c
Labels: PORT TO 7.0, ready to review

#2750 Ambiguous entering-wrong-state error
  db/sqloffload.c
Labels: cleanup

#2755 consumer: Fix handling of client controlled txn
  lua/sp.c
  tests/consumer.test/runit
  tests/consumer.test/t03.sh
Labels: PORT TO master

#2724 tracking admin mode connection
  db/sql.h
  db/sqlinterfaces.c
  net/net.c
  sqlite/ext/comdb2/connections.c
  tests/cdb2_admin.test/Makefile
  tests/cdb2_admin.test/README
  tests/cdb2_admin.test/runit
Labels: enhancement, refactor

#2700 A better alternative to find_tag_schema
  db/constraints.c
  db/indices.c
  db/indices.h
  db/osqlpfthdpool.c
  db/osqlshadtbl.c
  db/prefault.c
  db/record.c
  db/sqlstat1.c
  db/tag.c
  db/tag.h
  db/toblock.c
  db/verify.c
Labels: enhancement, ready to review

#2764 Fix typo from statement caching refactoring
  db/sql_stmt_cache.c
Labels: bug

#2767 Fix memory errors from recent refactoring
  db/sql_stmt_cache.c
Labels: bug

#2747 Fix implicit conversion from String to Datetime
  sqlite/src/dttz.c
  sqlite/src/vdbe.c
  sqlite/src/vdbeInt.h
  sqlite/src/vdbeaux.c
  tests/datetime.test/t16.expected
  tests/datetime.test/t16.sql
  tests/datetime.test/t17.expected
  tests/datetime.test/t17.sql
Labels: PORT TO 7.0, SQLite, bug, ready to review

#2768 Fix memory leak for fastsql queries with hints
  db/sql_stmt_cache.c
Labels: PORT TO 7.0, bug

#2770 added support for 'nonsql' metric'
  db/comdb2.c
  db/comdb2.h
  db/db_metrics.c
Labels: R7

#2773 added support for 'nonsql' metric'
  db/comdb2.c
  db/comdb2.h
  db/db_metrics.c
Labels: PORT TO 7.0
