Repository bloomberg/comdb2, pull requests merged in 2022-09, with the labels that each got.

#3400 Fix for missing log in longreqs file after a long chunked transaction completes
  db/sqlinterfaces.c
Labels: PORT TO master

#3403 cdb2sql: option to connect to master
  tools/cdb2sql/cdb2sql.cpp
Labels: feature

#3387 Print queries and client info on too many verify errors
  db/db_tunables.c
  db/db_tunables.h
  db/osql_srs.c
  db/osql_srs.h
  db/sqlinterfaces.c
  tests/tunables.test/t00_all_tunables.expected
Labels: enhancement

#3405 Fix ufid abort in rep-verify-match
  berkdb/dbreg/dbreg_rec.c
  berkdb/dbreg/dbreg_util.c
  tests/ufid_recovery.test/Makefile
  tests/ufid_recovery.test/lrl.options
  tests/ufid_recovery.test/runit
Labels: bug

#3419 Tweak the delayed-file-deletion logic
  bdb/file.c
Labels: bug
