Repository bloomberg/comdb2, pull requests merged in 2022-04, with the labels that each got.

#3206 Fixing a minor memory leak in fileid hash
  berkdb/db/db.c
Labels: bug

#3128 cdb2api: Get hostname from a cached FD
  cdb2api/cdb2api.c
  cdb2api/cdb2api.h
  docs/pages/programming/c_api.md
  tests/tools/api_events.c
Labels: enhancement

#3205 Implementing comdb2_memstats system table
  docs/pages/programming/system_tables.md
  mem/mem.c
  mem/mem.h
  sqlite/CMakeLists.txt
  sqlite/ext/comdb2/comdb2systblInt.h
  sqlite/ext/comdb2/memstats.c
  sqlite/ext/comdb2/tables.c
  tests/auth.test/t09.expected
  tests/bplog_leaks.test/runit
  tests/cdb2sql.test/t00.expected
  tests/clientstats_leaks.test/runit
  tests/comdb2sys.test/comdb2sys.expected
  tests/dohsql_leaks.test/runit
  tests/mem_be_nice.test/runit
  tests/op_makerecord.test/runit
  tests/rootpagememleak.test/runit
  tests/sql_datetime_interval_arithmetic_leak.test/runit
  tests/sql_func_mem_leak.test/runit
  tests/systbl_proc_leak.test/runit
  tests/temp_table_cursor_leak.test/runit
  tests/temp_table_truncate_leak.test/runit
  tests/userschema.test/t00.expected
Labels: enhancement

#3234 Fix collection type for connection_to_sql_ratio metric
  db/db_metrics.c
Labels: PORT TO master
