Repository bloomberg/comdb2, pull requests merged in 2022-05, with the labels that each got.

#3241 Get client side address after validation
  util/portmuxusr.c
Labels: PORT TO 7.0

#3242 Exclude consumers from periodic logging of long running requests
  db/reqlog.c
  lua/sp.c
  lua/sp.h
Labels: PORT TO master

#3243 Fix memory leaks in serializable and selectv range check
  db/reqlog.c
  db/toblock.c
Labels: bug, PORT TO 7.0

#3251 fix sorted dohsql capacity issue; stop dohsql if client disconnects
  db/dohsql.c
  db/sql.h
  db/sqlglue.c
  tests/unionpar_maxqueue.test/runit
Labels: bug

#3272 ssl: option to always allow local connections
  db/ssl_bend.c
  plugins/newsql/newsql_evbuffer.c
  plugins/newsql/newsql_sbuf.c
  util/ssl_glue.c
  util/ssl_glue.h
  util/ssl_io.c
Labels: PORT TO 7.0

#3277 SSL metrics
  db/db_metrics.c
  db/metrics.h
  db/sql.h
  db/sqlinterfaces.c
  db/ssl_bend.c
  plugins/newsql/newsql_evbuffer.c
  plugins/newsql/newsql_sbuf.c
  sqlite/ext/comdb2/connections.c
  tests/simple_ssl.test/runit
Labels: enhancement
