Repository bloomberg/comdb2, pull requests merged in 2022-03, with the labels that each got.

#3153 do not get a curtran in recover_deadlock if we do not have one already
  db/sqlglue.c
Labels: bug

#3154 do not get a curtran in recover_deadlock if we do not have one already
  db/sqlglue.c
Labels: bug

#3147 do not use a permanent field for a temp action, use an argument
  db/comdb2.c
  db/comdb2.h
  db/config.c
  db/tag.c
  schemachange/sc_add_table.c
  schemachange/sc_alter_table.c
  schemachange/sc_fastinit_table.c
  schemachange/sc_struct.c
  schemachange/schemachange.c
Labels: cleanup

#3155 Less spew from ENOTCONN
  db/reqlog.c
Labels: cleanup

#3167 do not assume there is a sc running when failing cmacc parsing
  db/comdb2.c
  db/comdb2.h
  db/config.c
  db/tag.c
  schemachange/sc_add_table.c
  schemachange/sc_alter_table.c
  schemachange/sc_fastinit_table.c
  schemachange/sc_struct.c
  schemachange/schemachange.c
Labels: bug

#3117 Minimal change to address shadow table memory leak
  db/osqlshadtbl.c
Labels: bug

#3091 Sending smartbeats for long running transactions
  db/osqlcheckboard.c
  db/osqlcheckboard.h
  tests/smartbeats.test/Makefile
  tests/tools/smartbeats.c
Labels: enhancement

#3133 Support providing connection parameters via properties
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/Driver.java
Labels: JDBC

#3130 Don't drain the cursor when closing the ResultSet or Connection
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/Comdb2Connection.java
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/Comdb2Handle.java
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/Driver.java
Labels: JDBC

#3214 Change systable access error to match user table access error
  db/sqlglue.c
  tests/auth.test/t11.expected
Labels: PORT TO master
