Repository bloomberg/comdb2, pull requests merged in 2022-01, with the labels that each got.

#3067 Reduce libevent overhead
  db/sqlinterfaces.c
  net/net_appsock.h
  net/net_evbuffer.c
  net/sqlwriter.c
  plugins/newsql/newsql_evbuffer.c
Labels: enhancement

#3040 Remove support for non-WITH_SSL build
  CMakeLists.txt
  bbinc/sbuf2.h
  bdb/info.c
  cdb2api/CMakeLists.txt
  cdb2api/cdb2api.c
  cdb2api/cdb2api.h
  db/CMakeLists.txt
  db/comdb2.c
  db/config.c
  db/db_access.c
  db/fdb_fend.c
  db/process_message.c
  db/sqlglue.c
  lua/CMakeLists.txt
  net/net.c
  net/net_int.h
  plugins/newsql/newsql_sbuf.c
  plugins/remsql/fdb_comm.c
  tests/cdb2api_unit.test/unit_get_comdb2db_hosts.c
  tests/smoketest/Dockerfile.nossl.build
  tests/smoketest/Makefile
  tests/tools/cdb2api_unit.c
  tools/cdb2_sqlreplay/CMakeLists.txt
  tools/cdb2sql/CMakeLists.txt
  tools/pmux/CMakeLists.txt
  util/CMakeLists.txt
  util/sbuf2.c
Labels: cleanup, ready to review

#3092 Fix crash in osql_repository_session_exists
  db/osqlrepository.c
Labels: bug

#3096 Fix a race condition in the if-progressing-on-master check
  db/osqlrepository.c
Labels: bug

#3100 enable micro_commit only if rowlocks enabled
  bdb/tran.c
Labels: bug

#3099 trivial fix and cleanup in mixed sql tags case
  db/toblock.c
Labels: bug

#3098 remove some unused code, simplify result in logical txn
  bdb/bdb_api.h
  bdb/bdb_int.h
  bdb/tran.c
Labels: cleanup

#3075 de-spaghetti-zing the scdone_callback on replicant
  bdb/bdb_schemachange.c
  bdb/bdb_schemachange.h
  schemachange/sc_callbacks.c
  schemachange/sc_global.c
  schemachange/sc_global.h
  schemachange/sc_queues.c
  schemachange/sc_queues.h
  tests/TODO
Labels: cleanup

#3107 fix non-blkseq schema change removal of old files
  db/toblock.c
Labels: bug

#3082 fix versioning across shards
  db/osqlcomm.c
  db/osqlsqlthr.c
  db/views.c
  db/views.h
  schemachange/sc_add_table.c
  schemachange/sc_add_table.h
  schemachange/sc_struct.c
  schemachange/schemachange.c
  schemachange/schemachange.h
  sqlite/src/comdb2build.c
  tests/timepart_retention1.test/run.log.alpha
Labels: bug

#3106 Fewer temptables for new snapshot
  bdb/file.c
  tests/newsi_temptables.test/Makefile
  tests/newsi_temptables.test/lrl.options
  tests/newsi_temptables.test/runit
Labels: enhancement
