Repository bloomberg/comdb2, pull requests merged in 2022-11, with the labels that each got.

#3521 Fix lazy_id_mutex deadlock
  bdb/file.c
  berkdb/dbreg/dbreg_util.c
Labels: bug

#3536 Fix linker error in debug build
  util/time_accounting.h
Labels: PORT TO master

#3470 Adjust zap of inline portion by one byte
  db/types.c
Labels: ready to review

#3554 netpoll
  db/db_tunables.h
  tests/tunables.test/t00_all_tunables.expected
Labels: cleanup

#3519 ssl prefer modes
  bbinc/ssl_support.h
  bdb/info.c
  cdb2api/cdb2api.c
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/Comdb2Handle.java
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/Constants.java
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/SSLIO.java
  cdb2jdbc/src/test/java/com/bloomberg/comdb2/jdbc/SSLPreferTest.java
  db/db_access.c
  db/ssl_bend.c
  docs/pages/config/ssl.md
  net/net.c
  plugins/newsql/newsql_evbuffer.c
  plugins/newsql/newsql_sbuf.c
  tests/setup
  tests/ssl_prefer.test/Makefile
  tests/ssl_prefer.test/nossl.testopts
  tests/ssl_prefer.test/runit
  util/ssl_io.c
  util/ssl_support.c
Labels: feature

#3490 cdb2api: shut down SSL before donating to sockpool
  cdb2api/cdb2api.c
Labels: bug

#3543 ddl for schemachange force mode
  db/comdb2.c
  db/comdb2.h
  db/db_tunables.c
  db/db_tunables.h
  schemachange/sc_schema.c
  sqlite/src/comdb2build.c
  sqlite/src/comdb2build.h
  sqlite/src/parse.y
  sqlite/tool/mkkeywordhash.c
  tests/auth.test/t09.expected
  tests/comdb2sys.test/comdb2sys.expected
  tests/sc_force.test/Makefile
  tests/sc_force.test/README
  tests/sc_force.test/expected
  tests/sc_force.test/lrl.options
  tests/sc_force.test/runit
  tests/sc_force.test/t1.csc2
  tests/sc_force.test/t2.csc2
Labels: PORT TO master
