Repository bloomberg/comdb2, pull requests merged in 2022-08, with the labels that each got.

#3358 Zap after byte/blob/string, Add tunable for disabling zapping on rebuild
  db/comdb2.c
  db/db_tunables.c
  db/db_tunables.h
  db/types.c
  schemachange/sc_records.c
Labels: PORT TO 7.0

#3370 Fix weighted_standing_queue test
  tests/weighted_standing_queue.test/runit
Labels: testsuite

#3375 Always free both normalized sqls (fixes fingerprint mismatch bug)
  db/sqlinterfaces.c
  tests/fingerprints.test/t06.req
  tests/fingerprints.test/t06.req.out
Labels: bug

#3378 Fix cdb2_close test
  cdb2api/cdb2api.c
  tests/cdb2_close.test/runit
Labels: testsuite

#3389 Fix tunables test
  tests/tunables.test/t00_all_tunables.expected
Labels: testsuite
