Repository bloomberg/comdb2, pull requests merged in 2024-02, with the labels that each got.

#3194 Fixing memory leaks in drop-table and drop-lua-consumer
  bdb/bdb_access.c
  bdb/bdb_api.h
  bdb/file.c
  bdb/llmeta.c
  db/sqloffload.c
  schemachange/sc_callbacks.c
  schemachange/sc_queues.c
Labels: bug, ready to review

#4229 Do not send intrans results during replays
  db/db_tunables.c
  db/db_tunables.h
  db/osqlcomm.c
  db/sqlinterfaces.c
  tests/replay_trans.test/Makefile
  tests/replay_trans.test/README
  tests/replay_trans.test/runit
Labels: PORT TO 7.0

#4137 {173891382}: Capturing remote queries and their fingerprints
  plugins/remsql/fdb_comm.c
  tests/remsql.test/runit
Labels: enhancement
