Repository bloomberg/comdb2, pull requests merged in 2024-10, with the labels that each got.

#4631 New remsql version (standalone queries only) that runs over cdb2api.
  cdb2api/cdb2api.c
  db/comdb2.h
  db/db_tunables.c
  db/db_tunables.h
  db/fdb_fend.c
  db/fdb_fend.h
  db/fdb_fend_cache.c
  db/sql.h
  db/sqlglue.c
  db/sqlinterfaces.c
  plugins/newsql/newsql.c
  plugins/remsql/fdb_comm.c
  tests/auth_dba.test/t00.sql
  tests/simple_remsql.test/cdb2api.testopts
  tests/tunables.test/t00_all_tunables.expected
Labels: ready to review

#4689 [8.0]{176316843}: Adding local-cache flag to clnt
  cdb2api/cdb2api.c
  db/sql.h
  db/sqlinterfaces.c
  plugins/newsql/newsql.c
  plugins/newsql/newsql.h
  plugins/newsql/newsql_evbuffer.c
  plugins/newsql/newsql_sbuf.c
  sqlite/ext/comdb2/connections.c
Labels: ready to review, R8

#4688 {176316843}: Adding local-cache flag to clnt
  cdb2api/cdb2api.c
  db/sql.h
  db/sqlinterfaces.c
  plugins/newsql/newsql.c
  plugins/newsql/newsql.h
  plugins/newsql/newsql_evbuffer.c
  sqlite/ext/comdb2/connections.c
Labels: ready to review

#4766 [8.0]{176307598}: Fixing recursive logmsg calls from ctrace
  util/ctrace.c
Labels: R8
