Repository bloomberg/comdb2, pull requests merged in 2024-09, with the labels that each got.

#4653 [8.0]{176398616}: Fixing race between sc and load-cache
  bbinc/debug_switches.h
  berkdb/mp/mp_fopen.c
  berkdb/mp/mp_sync.c
  tests/sc_load_cache_race.test/Makefile
  tests/sc_load_cache_race.test/lrl.options
  tests/sc_load_cache_race.test/runit
  util/debug_switches.c
Labels: R8

#4704 {176060832}: Ensuring non-negative from Java random number generator
  cdb2jdbc/src/main/java/com/bloomberg/comdb2/jdbc/Comdb2Handle.java
Labels: JDBC

#4696 R8 -- comdb2_files: skip watchdog and tmpdir contents
  db/comdb2.c
  sqlite/ext/comdb2/files.c
  tests/comdb2_files.test/lrl.options
  tests/comdb2_files.test/runit
Labels: R8

#4714 {176603116}: Improvements to the scope of valueFromFunction()
  sqlite/src/vdbemem.c
  tests/yast.test/funcs.test
Labels: ready to review

#4712 {176446246}: Fixing read-committed updates behind sc-cursor
  bbinc/blob_buffer.h
  bdb/bdb_verify.c
  db/osqlcomm.c
  db/osqlshadtbl.c
  db/osqlsqlthr.c
  db/record.c
  db/types.c
  db/verify.c
  tests/sc_vutf8_blob2_upd_behind_cursor.test/t.recom_null_blobs/csc2
  tests/sc_vutf8_blob2_upd_behind_cursor.test/t.recom_null_blobs/expected
  tests/sc_vutf8_blob2_upd_behind_cursor.test/t.recom_null_blobs/insert
  tests/sc_vutf8_blob2_upd_behind_cursor.test/t.recom_null_blobs/new.csc2
  tests/sc_vutf8_blob2_upd_behind_cursor.test/t.recom_null_blobs/update
Labels: bug, ready to review

#4728 {176689231}: Porting SQLite fix for LEFT-JOIN using OR that matches no rows
  sqlite/src/vdbeaux.c
  tests/yast.test/whereD.test
Labels: bug, ready to review, SQLite

#4729 [8.0]{176689231}: Porting SQLite fix for LEFT-JOIN using OR that matches no rows
  sqlite/src/vdbeaux.c
  tests/yast.test/whereD.test
Labels: bug, SQLite, R8
